Homebrew/homebrew-bundle

bin/brewdle
cmd/brew-brewdler.rb
lib/brewdler/commands/install.rb

If this repo is renamed to e.g. `andrew/homebrew-brewdler` (or `Homebrew/homebrew-bundler` or whatever) then with this PR merged one will be able to:
```bash
brew tap mikemcquaid/brewdler # currently working but could instead be andrew/brewdler or Homebrew/bundler or whatever.
brew brewdler
```
The previous `gem` installation method will still work and this will just provide an alternate installation method that doesn't require any messing with `PATH`, any use of `gem` and autoupdates with `brew update`.
The implementation is still a bit hacky as-is so feel free to request I change the approach here and I'm happy to do so.

Add Homebrew "tap command" support

---

Readme.md

homebrew-cask has been an organization for a while now, no longer under `phinze/homebrew-cask`, but `caskroom/homebrew-cask`.

Readme.md: correct homebrew-cask tap

---

brewdler.gemspec
spec/dsl_spec.rb
spec/install_command_spec.rb

- Replace deprecated `should_receive` with `expect(...).to ...`
- Replace deprecated `stub` with `allow(...).to receive(...)`

Upgrade rspec

---

brewdler.gemspec

I have no idea why this was added in 99dab3359f3fa602fac63487703268ab83232392. Its not used by this library at all.
cc @andrew @jamesaanderson

Remove mime-types dependency

---

lib/brewdler/brew_installer.rb
lib/brewdler/cask_installer.rb
lib/brewdler/repo_installer.rb

Simply checks if `brew` or `brew-cask` load path rather than trying to execute and dump the output of expensive commands.
Invoking `brew info` on my machine adds an additional 2 seconds to every brew install and prints useless data like `35 kegs, 91540 files, 1.4G` to the output.
cc @mikemcquaid

Detect presence of brew and brew-cask commands

---

lib/brewdler/dsl.rb

I think we should keep #32 open for now but I changed `eval` to `instance_eval` which should be a bit more secure. Bundler seems to use `instance_eval` as well.

Change eval to instance_eval

---

spec/brewdumper_spec.rb
spec/dump_command_spec.rb

This commit fixes the following warning when invoking `bundle exec rake`
Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)

eliminate warning during the test

---

cmd/brew-brewdle.rb
lib/brewdler/dumper.rb
lib/brewdler/utils.rb
spec/cleanup_command_spec.rb
spec/dump_command_spec.rb
spec/dumper_spec.rb
spec/install_command_spec.rb

It can be useful if there're multiple Brewfile configurations.
e.g.
brew brewdle --file=Brewfile.osx
brew brewdle --file=Brewfile.linux

allowing custom Brewfile path in the argument

---

lib/bundle/cask_dumper.rb

Cask would add ` (!)` into cask name if the cask is not availabled or
some temporary errors.

cask dumper: chomp the trailing " (!)"

---

Readme.md
cmd/brew-bundle
lib/bundle/utils.rb

See the discussion in https://github.com/Homebrew/homebrew-bundle/issues/1.
This pull request fixes the shebang in `/cmd/brew-bundle` so that it can run on Linux. In Linux, the `#!/usr/bin/env` shebang previously tried to run the executable "ruby -W0", which returned the error:
/usr/bin/env: ruby -W0: No such file or directory
(See, for example, [Bash trace mode (bash -x) in the shebang](http://stackoverflow.com/q/24032641/2571049) on Stack Overflow.)
By changing this to `#!/bin/sh` and making the call to ruby with `exec ruby -x "$0" "$@"`, this problem is solved.
`man ruby` tells us for the flag `-x` that:
>      -x[directory]  Tells Ruby that the script is embedded in a message.  Leading garbage will be discarded until the first line that starts with ``#!'' and con-
tains the string, …

Fix shebang so brew bundle works on Linux

---

CODEOFCONDUCT.md
CONTRIBUTING.md

Using the same one as [Homebrew](https://github.com/Homebrew/homebrew/blob/master/CODEOFCONDUCT.md) itself.
Also added a note about it in `CONTRIBUTING.md` as well as a security section, also the same as Homebrew.

Added Homebrew code of conduct

---

lib/bundle/brew_dumper.rb
lib/bundle/brew_installer.rb
lib/bundle/cask_installer.rb
lib/bundle/commands/check.rb
lib/bundle/commands/cleanup.rb
lib/bundle/tap_installer.rb
spec/brewdumper_spec.rb
spec/brewinstaller_spec.rb
spec/check_command_spec.rb
spec/cleanup_command_spec.rb
spec/dumper_spec.rb
spec/spec_helper.rb
spec/tapdumper_spec.rb

Also some other general cleanup and refactoring and ensuring that tests have 100% coverage.
CC @xu-cheng

Support aliases.

---

lib/bundle/brew_dumper.rb

brew_dumper: handle missing keg in JSON.

---

cmd/brew-bundle
cmd/brew-bundle.rb

This means it'll use the Homebrew Ruby rather than whatever Ruby is in your path. This also means if you're using it to e.g. install some project dependencies to install a Ruby that does not already exist then
you do not need to do e.g. `RBENV_VERSION=system` first.
If we want to make it easier for people to run e.g. on 10.9 with an old Ruby (although I think it might be worth waiting for user requests first) we can loosen the `HOMEBREW_DEVELOPER` check in https://github.com/Homebrew/homebrew/pull/45816 to not require `HOMEBREW_DEVELOPER` to be set.
CC @xu-cheng for thoughts.

Rename command to `brew-bundler.rb`.

---

lib/bundle/brew_dumper.rb
spec/brewdumper_spec.rb

If we didn't get a keg back then ensure we don't try to read it in any form. Also, tweak how we read it so bad or missing data won't make it explode.
Closes https://github.com/Homebrew/homebrew-bundle/issues/125

BrewDumper: handle bad keg JSON more strictly.

---

cmd/brew-bundle.rb

Otherwise you can see issues with timezones. CC @zawaideh who I'm pretty sure just hit this.

Use the same time format for parsing commit.

---

spec/brew_installer_spec.rb
spec/check_command_spec.rb
spec/cleanup_command_spec.rb
spec/dump_command_spec.rb
spec/spec_helper.rb
spec/tap_installer_spec.rb

Currently, when we want to run the test suite, we must run `bundle exec rake spec`. When run `rake spec` alone, `without bundler exec`, an exception is thrown `NameError: uninitialized constant Bundler` because we when run with `bundle exec`, `bundler` is automated required for us.
This a confused behaviour because in the code, we don't use bundler. And in fact, if we remove all the bundler stuffs, then just run `rake spec`, the test will pass.
So i make some changes in the `spec_helper`. First, require `bundler` explicitly. Second, run all specs under `Bundler.with_clean_env`, which make the test easy to understand and separate setup test env with the actual test.

Require bundler explicitly

---

lib/bundle/dumper.rb
spec/dump_command_spec.rb

This makes failure faster.
```
$ time brew bundle dump
real  0m2.451s
user  0m2.060s
sys 0m0.314s
$ time brew bundle dump
Error: /Users/colin/Source/homebrew/homebrew-bundle/Brewfile already exists
real  0m0.260s
user  0m0.193s
sys 0m0.055s
```

Check for Brewfile existence before doing any work

---

cmd/brew-bundle.rb

When git is configured with `date=relative`, `git show -s --format=%cd`
prints commit date as `38 minutes ago`, which `Time.parse` is unable to parse.
Using `%cD` force git to print in RFC2822 style regardless of git config.

Use RFC2822 style when checking git commit date

---

Readme.md
lib/bundle/brew_installer.rb
spec/brew_installer_spec.rb

First off, thanks for making homebrew and Brewfiles. It's a boon for Mac development. :cake: 
This changes `restart_service: true` to only restart services if they’re installed or upgraded. Avoiding unnecessary restarts is faster, and less disruptive for developers who may be using those services while `brew bundle`'ing.
This changes the current default of restarting services on each `brew
bundle run`. If a user would like to keep the current behavior, they can specify `restart_service: :always` in their Brewfile.

restart_service only if formula installed or upgraded

---

lib/bundle/dsl.rb
spec/brew_dumper_spec.rb

@xu-cheng / @andrew / @mikemcquaid: just a bit of minor refactoring to the codebase, mainly to get rid of some annoying Ruby warnings in the `lib` and `spec` files, and a minor change to make a `case` statement a tad more idiomatic... hope you approve!  I've kept the individual commits very atomic, to make reviewing them as easy as possible.Thanks, @pvdb

Fix ruby issues

---

Readme.md
lib/bundle/brew_dumper.rb
lib/bundle/brew_installer.rb
lib/bundle/brew_services.rb
lib/bundle/dsl.rb
spec/brew_dumper_spec.rb
spec/brew_installer_spec.rb
spec/brew_services_spec.rb
spec/dsl_spec.rb
spec/install_command_spec.rb

Unlink and stop the service for conflicting formulae or those specified
by a `conflicts_with` argument. This is useful when using `brew bundle`
to manage the transition between e.g. `homebrew/versions` versions.
Similar to https://github.com/Homebrew/homebrew-bundle/pull/124
CC @josh @xu-cheng for thoughts.

Unlink and stop service for conflicting formulae.

---

lib/bundle/brew_services.rb

brew_services: escape formula name in regex.

---

Readme.md

This updates the README to reflect new URLs from the [Homebrew Core/Formula Separation](https://github.com/Homebrew/legacy-homebrew/issues/50650).

doco: update for Homebrew core/formulae split

---

lib/bundle/brew_dumper.rb
spec/brew_dumper_spec.rb

Fix to dumps args in same order when a formula installed with args specified in different order on different machines.
In current implementation, as I present below, there is the case that has difference about its order.
```diff
-brew 'gcc', args: ['with-jit', 'with-nls', 'with-all-languages']
+brew 'gcc', args: ['with-all-languages', 'with-jit', 'with-nls']
```

Fix to dumps fomula args in same order

---

lib/bundle/utils.rb
spec/mac_app_store_installer_spec.rb
spec/utils_spec.rb

Use Kernel.system instead of our own logic to handle verbose output. This
allows us to show progress bar for downloading.

Bundle.system: better way to handle verbose

---

cmd/brew-brewdle.rb
cmd/brew-brewdler.rb
cmd/brew-bundler.rb

These were used for transitional purposes and are no longer needed.
CC @UniqMartin

Remove aliases.

---

lib/bundle/brew_dumper.rb

We have started to record commit information in the HEAD prefix.

brew_dumper: fix HEAD installation

---

.travis.yml

We don't need to test against this version.

travis: don't build against Ruby 2.2.0.

---

cmd/brew-bundle.rb

Homebrew itself now depends on Ruby 2 so just depend on a new enough version of Homebrew.

cmd/brew-bundle.rb: don't check for Ruby 2.

---

lib/bundle/brew_dumper.rb
lib/bundle/brew_services.rb
lib/bundle/commands/check.rb
lib/bundle/commands/cleanup.rb
lib/bundle/utils.rb
spec/brew_services_spec.rb
spec/dumper_spec.rb
spec/utils_spec.rb

* check whether brew services is installed. Otherwise, `brew bundle dump`
will install brew services.
* remove duplicate codes on checking services started.
* avoid opportunistic regex, e.g. we should not match `started` in formula or
plist file name.

brew services related fix

---

lib/bundle/brew_dumper.rb
spec/brew_dumper_spec.rb

This should help make the dump more deterministic, but I'm not sure if it's a complete fix for https://github.com/Homebrew/homebrew-bundle/issues/157

Sort dependencies by name during tsort

---

lib/bundle/dsl.rb

Make this `rescue` broader to avoid having confusing error messages like in #203 (and to not tell people to report it).

dsl: rescue all exceptions.

---

Readme.md

https://github.com/Homebrew/homebrew-bundle/pull/212 changed the **Coverage Status** badge to **CodeCov** but the actual link was left pointing to **Coveralls**. I believe that this was simply an accidental oversight, hence this PR, but if it was intentional feel free to summarily close this PR.
@MikeMcQuaid You are probably the best one to look at this since the change was your PR to begin with.

README: point Coverage Status link to CodeCov page

---

lib/bundle/brew_dumper.rb

Not service_restart as was outputted and unused.

brew_dumper: use restart_service correctly.

---

lib/bundle/mac_app_store_dumper.rb

Newer versions of `mas` output the version as part of the name. Omit this to avoid `brew bundle dump` churn.

mac_app_store_dumper: omit versions.

---

lib/bundle/bundle.rb
spec/spec_helper.rb

Fix the check now that `brew-cask` has moved into Homebrew/brew.
CC @DomT4 to check this fixes your issue.
Fixes #226.

bundle: fix brew cask installation detection.

---

lib/bundle/brew_dumper.rb
lib/bundle/brew_installer.rb
lib/bundle/commands/check.rb
lib/bundle/commands/cleanup.rb
spec/brew_dumper_spec.rb

Use the formula’s `oldname` to handle `Brewfile`s that are still using the old names from before a formula rename. In these cases `brew bundle` will still install things fine but `brew bundle check` would always fail.
CC @technicalpickles who has seen this before.

Improve renamed formula behaviour

---

lib/bundle/bundle.rb
lib/bundle/mac_app_store_installer.rb
spec/mac_app_store_installer_spec.rb

This PR would resolve the issue #233.
When the user is not signed in to the Mac App Store, it will open the `App Store.app` and prompt for logging in instead of failing to install all apps specified for `mas` in the `Brewfile`.
Clarification of the chosen command:
`mas signin` requires to provide an Apple ID, which is not possible to provide at the time of the call. So I opted for `mas signin --dialog ''`. The `--dialog` option opens the login dialog of the `App Store.app` and passes the string after the argument to the email field of the dialog (therefore we pass an empty string)

Add check to ensure mas is signed in (#233)

---

.travis.yml
spec/spec_helper.rb

Otherwise there’s annoying warnings when doing a local test run.

spec_helper: only submit coverage for CI.

---

lib/bundle/brew_dumper.rb

Previously it was doing e.g. `!f["pinned"].nil?` which would actually end up being `true` if `f["pinned"]` was `false`. As a result of both `pinned?` and `outdated?` having this behaviour it broke `brew bundle check` checking if formulae were outdated and `brew bundle`
from upgrading them.

brew_dumper: fix handling of pinned/outdated.

---

lib/bundle/dsl.rb

This is for the new version formula naming in homebrew/core.

dsl: include @ into formula regex.

---

Readme.md

The new docs site doesn't allow deep linking so just remove this link.

Remove old link.

---

lib/bundle/mac_app_store_dumper.rb

To my knowledge, the App Store doesn't have a concept of dependencies, so the objection to alphabetizing mentioned in #242 doesn't apply.
Fixes #256.
(This is literally the first time I've looked at, much less written, any Ruby. Apologies for code quality or whatever else I may have messed up. 😄 )

Alphabetize `mas list` when dumped to Brewfile

---

lib/bundle/bundle.rb

Otherwise `brew bundle dump` (the only place that actually uses this method) may auto-tap caskroom/cask and put the tap output when `brew cask list` is called.
Fixes #265.

bundle: need Caskroom and tap for cask installed.

---

lib/bundle/brew_services.rb

States such as `error` or `unknown` both indicate an intention from the user that this service be started.

brew_services: consider "not stopped" as started.

---

cmd/brew-bundle.rb

`/usr/local/bin` can be filtered out by e.g. Homebrew's environment filtering feature so re-add it to the PATH if missing to make sure.

brew-bundle: add `brew` back to PATH if missing.

---

Readme.md
lib/bundle/brew_dumper.rb
lib/bundle/cask_dumper.rb
lib/bundle/mac_app_store_dumper.rb
lib/bundle/tap_dumper.rb
spec/brew_dumper_spec.rb
spec/cask_dumper_spec.rb
spec/dumper_spec.rb
spec/tap_dumper_spec.rb

This better matches Homebrew's (and Rubocop's) general style guidelines and also better handles textual content such
as the `mas` lines' `name`.
This will cause an annoying diff when running `brew bundle dump` but this was a change that feels worth that minor,
one-time annoyance.
Fixes #271.

Use double-quotes in Brewfiles.

---

lib/bundle/bundle.rb
spec/spec_helper.rb

After #275, we ran into CI error:
```
brew bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Counting objects: 57, done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 57 (delta 5), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (57/57), 29.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (5/5), done.
Tapped 0 formulae (72 files, 157.6KB)
Error: undefined method `success?' for nil:NilClass
Please report this bug:
https://github.com/Homebrew/homebrew-bundle/issues/
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/bundle.rb:13:in `block in system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/bundle.rb:8:in `popen' …
```

Move requirement of English stdlib to library

---

lib/bundle/brew_dumper.rb
lib/bundle/commands/check.rb
spec/check_command_spec.rb

If two formulae have services that need to start and the first is
already started, the previous code would exit early from the method and
not check the second service. By switching to `next`, we properly
compare each service until one is found that needs to be started.
Note: The second commit is mostly for style's sake, and can be removed if requested. `Bundle::BrewInstaller#resolve_conflicts!` also has the potentially-confusing return from a block, but an early-exit is desirable there, so I've left it.

Check command will check all services that might need starting, instead of just the first

---

cmd/brew-bundle.rb

Improve the `HOMEBREW_VERSION` check to be based on the global constant rather than the time of the HOMEBREW_REPOSITORY's last commit.
CC @JCount
Fixes https://github.com/Homebrew/brew/issues/3045
Fixes https://github.com/Homebrew/homebrew-bundle/issues/282

brew-bundle: improve HOMEBREW_VERSION check.

---

lib/bundle/cask_dumper.rb

Commands like `cleanup` and `check` would provide incorrect information
if a cask from a tap other than caskroom/cask was installed. While the
Brewfile might include the tap name (e.g. "caskroom/version/foo"),
CaskDumper would report the installed cask as "foo". Now that CaskDumper
provides the full name of the cask, comparisons between a Brewfile and
the installed state correctly consider the tap the cask is from.
This requires homebrew/brew#2878, which adds the flag, to be merged first.

CaskDumper uses cask full-name

---

.travis.yml
lib/bundle/dsl.rb
spec/dsl_spec.rb

I have a `Brewfile` like this:
```ruby
brew "rbenv"
brew "ruby-build"
```
When I run `brew bundle` or `brew bundle check`, I get:
```text
~/project#master$ brew bundle check
Error: Invalid Brewfile: can't modify frozen String
```
With `HOMEBREW_DEBUG=true`:
```text
~/project#master$ HOMEBREW_DEBUG=true brew bundle check
Error: Invalid Brewfile: can't modify frozen String
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:30:in `instance_eval'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:130:in `sanitize_tap_name'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:107:in `tap'
(eval):3:in `process'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/dsl.rb:30:in `instance_eval' …
```

Bundle DSL: handle names as frozen string literals

---

Readme.md
cmd/brew-bundle.rb
lib/bundle/brew_installer.rb
spec/brew_installer_spec.rb
spec/dsl_spec.rb

For versioned formulae e.g. `mysql@5.6` it may be desirable to automatically link formulae after that are installed by Homebrew/bundle if you are only going to have one version of MySQL on a system and you wish it to be in your `PATH` by default.

Allow automatically linking formulae.

---

.travis.yml
lib/bundle.rb

This matches the version Homebrew itself is now using.

.travis.yml: use Ruby 2.3.

---

lib/bundle/commands/cleanup.rb
spec/cleanup_command_spec.rb

When searching `current_formulae` for a formula, it was not found if the
formula was from a custom tap and had a `full_name` different from its
`name`. This caused all of its dependencies to be missed.
Fixes #301

Do not uninstall dependencies for custom formulae

---

lib/bundle/brew_dumper.rb
lib/bundle/commands/cleanup.rb
spec/brew_dumper_spec.rb
spec/cleanup_command_spec.rb

If a formula has not been poured from a bottle, its build dependency will be used for upgrades and should be kept around.
There's an argument for getting rid of build dependencies during a cleanup (they're not needed for runtime), but it was unexpected for me. Upgrading a formula built from source is very likely, so it seems like a good idea to keep build dependencies around.

Only clean up build dependencies for bottles

---

lib/bundle/brew_installer.rb
spec/cleanup_command_spec.rb
spec/dsl_spec.rb

Use `<<~EOS` everywhere instead. Fixes #316.

Update deprecated EOS usage

---

lib/bundle/cask_installer.rb
lib/bundle/commands/check.rb
lib/bundle/mac_app_store_installer.rb
spec/cask_installer_spec.rb
spec/mac_app_store_dumper_spec.rb
spec/mac_app_store_installer_spec.rb
spec/spec_helper.rb

These tools now both have `upgrade` and `outdated` commands so let's use
them everywhere that makes sense.
Additionally, because it helped by debug, automatically filter out
`rspec` tests with `:focus`.
Fixes #309.

Add upgrade/outdated support to mas and cask.

---

Gemfile.lock

I encountered an error saying that `filter_run_when_matching` was missing on the RSpec config object when running specs for #324. It turns out that this method was added in rspec 3.5.0 and I had an older version of RSpec installed and that older version met the requirement in the Gemfile of "any version!"

Sets minimum rspec version to 3.5.0

---

lib/bundle/mac_app_store_installer.rb
spec/mac_app_store_installer_spec.rb

This was previously always showing `mas` apps as outdated incorrectly.

mac_app_store_installer: fix outdated handling.

---

cmd/brew-bundle.rb
lib/bundle/brew_dumper.rb
spec/brew_dumper_spec.rb

This option outputs above each dependency a comment containing a description when the dependency has a description associated with it.
Right now, only Homebrew formulae have descriptions. Casks, taps, and mas dependencies do not have descriptions available.
Fixes #322

Adds --describe option to brew bundle dump

---

lib/bundle/tap_dumper.rb
spec/tap_dumper_spec.rb

Little bit easier to read when sorted by name and it will match the output of `brew tap`.

tap_dumper: sort by name

---

lib/bundle/commands/cleanup.rb
spec/cleanup_command_spec.rb

It makes sense to also run `brew cleanup` on `brew bundle cleanup` so it can be a one stop shop for cleaning up your Homebrew.

cleanup: run brew cleanup.

---

lib/bundle/mac_app_store_dumper.rb
spec/mac_app_store_dumper_spec.rb

During a routine `brew bundle` I came across the following exception
(which manages to halt all commands):
```
Error: Invalid Brewfile: uninitialized constant #<Class:#<Bundle::Dsl:0x00000101a5d898>>::Install
```
Searching around the issue tracker, I noticed a couple of [existing](https://github.com/Homebrew/homebrew-bundle/issues/308)
[issues](https://github.com/Homebrew/homebrew-bundle/issues/321) where this was occurring when the `mas list` output included
an application from the app store that wasn't formatted as `brew bundle`
expected. Sure enough, this was also my issue.
```
497799835 Xcode (9.2)
409183694 Keynote (8.1)
408981434 iMovie (10.1.8)
Install macOS High Sierra (13105)
409201541 Pages (7.1)
682658836 GarageBand (10.3.1)
409203825 Numbers (5.1)
```
Taking a look at the …

 Ensure `MacAppStoreDumper` only dumps valid app details

---

.travis.yml
spec/cleanup_command_spec.rb

Ensure that `brew cleanup` isn't run when running the test suite.
Fixes #353.

cleanup_command_spec: add missing mocks.

---

cmd/brew-bundle.rb

Since this is now a Ruby script required by Homebrew we want to tweak the way that exits are handled so that Homebrew outputs them and sets the exit code nicely as expected.

cmd/brew-bundle.rb: improve exit usage.

---

cmd/brew-bundle.rb

Display all on one line and allow terminals to do the wrapping. This is consistent with other lines (and commands).

cmd/brew-bundle: tweak check help output.

---

cmd/brew-bundle.rb

I was uncertain what difference the `--zap` flag would have when running `brew bundle cleanup` and had to take a look at the source to find out. Adding a brief explanation helps clarify the difference.

Add docs for zap flag

---

lib/bundle/mac_app_store_dumper.rb
spec/mac_app_store_dumper_spec.rb

#349 introduced a basic regex for determining if the app names provided
via `mas` were valid and would discard any that failed to meet this
requirement. Apple are [quite generous](https://developer.apple.com/app-store/review/guidelines/#accurate-metadata) when it comes to what you can
name an application and in essence, the only restriction they place on
it is that it cannot infringe on a trademark and must be under 30
characters long.
This means that there are real applications that fail to meet the
initial regex of `\w\s` due to using non-alphanumeric characters.
"Pastebin It!" is an example of this.
To account for this, I've extended the regex to accept any character
for the `name` portion of the regex. This might look fragile (and I
would agree!) however it is the safest way to ensure …

Extend valid `mas` app name regex

---

lib/bundle/brew_dumper.rb
lib/bundle/lister.rb

Fixes warnings emitted in tests for #372 
1. https://travis-ci.org/Homebrew/homebrew-bundle/builds/435899798#L1708
2. https://travis-ci.org/Homebrew/homebrew-bundle/builds/435899798#L1711

Corrects two Rubocop warnings new since project-wide config changed

---

lib/bundle/bundle.rb
lib/bundle/commands/cleanup.rb
lib/bundle/commands/exec.rb
lib/bundle/mac_app_store_installer.rb
spec/mac_app_store_installer_spec.rb
spec/spec_helper.rb
spec/stub/formula.rb
spec/stub/formulary.rb
spec/stub/global.rb
spec/stub/os.rb
spec/stub/tap.rb
spec/stub/utils/formatter.rb

- see if app can be skipped because it doesn’t need upgrade
- don’t try to sign in on Mojave (it doesn’t work)
- only fail if app actually needs installed/upgraded
- don’t print `mas account` output; just use exit code
- add `MacOS` stub and cleanup existing stub code
Fixes #370

mas: better handle signin failure

---

lib/bundle.rb
lib/bundle/brewfile.rb
lib/bundle/bundle.rb
lib/bundle/checker.rb
lib/bundle/commands/cleanup.rb
lib/bundle/commands/exec.rb
lib/bundle/commands/install.rb
lib/bundle/commands/list.rb
lib/bundle/dumper.rb
spec/brewfile_spec.rb

`Bundle.brewfile` and `Dumper.dump_brewfile` contained duplicate logic
for locating the `Brewfile`. This logic now resides in the `Brewfile`
module.
This is the first step in addressing https://github.com/Homebrew/homebrew-bundle/issues/368

Extract `Brewfile` locator logic to its own module

---

spec/bundle/brew_dumper_spec.rb

These `let` blocks aren't needed.

brew_dumper_spec: remove copy/pasta.

---

lib/bundle/brewfile.rb
spec/bundle/brewfile_spec.rb

Doesn't make sense to attempt to dump to stdin.
Fixes #405.

brewfile: use /dev/stdout for dump command.

---

README.md
cmd/brew-bundle.rb
lib/bundle/brew_dumper.rb
spec/bundle/brew_dumper_spec.rb

I like to use `brew bundle` to record what home-brew packages I have installed on a cron job, just for workstation automation purposes. Whenever I have a service started (`postgresql` comes up a lot), the output of my cron job that dumps my brewfile alternates between containing `restart_service: true` for those formulae and not containing it, which results in a lot of noisy changes to my brewfile.
I thought it might be nice to have a `--no-restart` flag for the dump command to never include the `restart_service` part of the dump.
I'm not sure if my use case is very common, but this feature would be very helpful for me. Thanks!

Adding `--no-restart` flag to `dump` command

---

lib/bundle/brew_installer.rb

brew_installer: recheck if up to date on failed upgrade.

---

lib/bundle/brewfile.rb
spec/bundle/brewfile_spec.rb
spec/spec_helper.rb
spec/stub/object.rb

Adds support for `HOMEBREW_BUNDLE_FILE` as a way to specify the location
of the `Brewfile` to be used by `brew bundle` commands.
Specifying `HOMEBREW_BUNDLE_FILE` when `--global` or `--file` are also
specified results in an error.
Existing behavior wherein `--global` overrides `--file` with no error is
preserved. This could be revisited in the future, the code in
`brewfile.rb` would likely need further refactoring.
* This addresses an issue initially raised in https://github.com/Homebrew/homebrew-bundle/issues/368.

Allow `Brewfile` location to be specified in ENV

---

cmd/brew-bundle.rb

We use ActiveSupport internally now so need at least ~2.0.0 (but let's go for a newer 2.1.0 to be safer).
Fixes #509.

brew-bundle: require newer Homebrew version.

---

lib/bundle/brewfile.rb
spec/bundle/brewfile_spec.rb

Don't check for `ARGV.include?` as that's not always `true` when `--file` is specified.
Fixes #507
Closes #508

lib/bundle/brewfile: fix file parameter handling.

---

lib/bundle/cask_dumper.rb

Allow either in a `Brewfile` to avoid confusion such as in #506.

cask_dumper: use full and short names.

---

lib/bundle/commands/cleanup.rb

Fixes regression introduced in #514 where these would be marked for removal by `brew cleanup`.
Fixes #519.

cleanup: fix handling of tapped casks.

---

lib/bundle/skipper.rb

This will allow skipping `mas` apps with spaces in the name.
Fixes #525.

skipper: allow `mas` IDs.

---

lib/bundle/dsl.rb
spec/bundle/commands/check_command_spec.rb
spec/bundle/dsl_spec.rb

The current `brew bundle check` output for a brewfile that specifies a service
is the somewhat unhelpful default `to_s` of the `Bundle::Dsl::Entry` struct.
```
brew bundle can't satisfy your Brewfile's dependencies.
→ Service #<Bundle::Dsl::Entry:0x00007fcf5285b7a8> needs to be started.
Satisfy missing dependencies with `brew bundle install`.
```
This PR adds a trivial `to_s` implementation to improve the output:
```
brew bundle can't satisfy your Brewfile's dependencies.
→ Service def needs to be started.
Satisfy missing dependencies with `brew bundle install`.
```
Fixes #534.

Fix brew bundle check output for services

---

cmd/brew-bundle.rb
lib/bundle/commands/cleanup.rb

Shift whitespace to match other `brew help <cmd>` output and fix up grammar.

Adjust documentation output formatting

---

lib/bundle/extend/os/linux/skipper.rb

- The output was unclear in the case that you had a Brewfile with a cask
and then a standard formula (eg Linux formula) of the same name which
installs fine.
Before:
```
Using aws-vault
Skipping aws-vault (on Linux)
```
After:
```
Using aws-vault
Skipping cask aws-vault (on Linux)
```

skipper: Specify the type of the formula being skipped on Linux

---

lib/bundle/brew_installer.rb
spec/bundle/brew_installer_spec.rb
spec/stub/formula.rb

Check the authoritative source from `Formula#outdated?` rather than relying exclusively on our cache. This also avoids busting the cache or displaying weird messages in verbose mode where it fails but we handle it after the fact.
CC @kbd
Fixes #551

brew_installer: fix dependency upgrades (again).

---

.github/workflows/tests.yml

While merging an automated bundle update, I seen an annoated beta message below the files section that pointed out we should be using `ruby-version` not `version` when using the `actions/setup-ruby@v1` container.
See https://github.com/Homebrew/homebrew-bundle/pull/568/files for the message.

Use `ruby-version` instead of `version`

---

lib/bundle/cask_dumper.rb
lib/bundle/commands/cleanup.rb
spec/bundle/cask_dumper_spec.rb
spec/bundle/commands/cleanup_command_spec.rb

Fixes https://github.com/Homebrew/homebrew-bundle/issues/480
When running `brew bundle cleanup`, cask formula dependencies weren't being added to the list of kept formulae.
This change checks that for each kept cask, we add any formula dependencies to the list of kept formulae.
1. `brew cask install qlcolorcode`
2. `brew bundle dump`
3. `brew bundle cleanup`
When running `brew bundle cleanup` the listed formulae to be uninstalled **will** include `highlight` (a dependency of the `qlcolorcode` cask) and `lua` (a dependency of the `highlight` formula)
When running `brew bundle cleanup` the listed formulae to be uninstalled **won't** include `highlight` (a dependency of the `qlcolorcode` cask) or `lua` (a dependency of the `highlight` formula)

Keep cask formula dependencies in "bundle cleanup"

---

.github/workflows/tests.yml
Gemfile.lock

This will allow use with the version bundled with Ruby 2.6.

Gemfile.lock: downgrade "bundled with".

---

lib/bundle/locker.rb
spec/bundle/locker_spec.rb

It may be the `Brewfile` is readable but not writable.

locker: handle permission errors.

---

lib/bundle/locker.rb
spec/bundle/locker_spec.rb

Name the lockfile after the name of the Brewfile when the default is overridden
using either `--file` or `HOMEBREW_BUNDLE_FILE`.
Fixes #595.

Match Brewfile name in lockfile name

---

cmd/brew-bundle.rb

This should make it more obvious what the specific versions involved are so it can be more easily debugged.

cmd/brew-bundle: improve outdated messaging.

---

README.md

Move backtick to include only the option name

---

lib/bundle/cask_dumper.rb
spec/bundle/cask_dumper_spec.rb
spec/stub/utils.rb

cask_dumper: handle bad JSON.

---

lib/bundle/locker.rb

Adds a trailing newline to the lock file to make its last line conform to the [POSIX standard for lines](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206):
> 3.206 Line
>
> A sequence of zero or more non- \<newline\> characters plus a terminating \<newline\> character.
I'm not that fluent in rspec so I wasn't sure how to add a test that mocks `Pathname` to actually  check what is written to the lock file in the locker spec. Let me know if I should have a deeper look into that!

Add trailing newline to lock file

---

lib/bundle/extend/os/linux/skipper.rb

- Casks are automatically skipped on Linux. When there's a Brewfile used on both macOS and Linux, there's usually Casks in it. This leads to `tap "homebrew/cask"` being present and causes the Cask tap to be installed on Linux too, even though Casks don't work on Linux and `cask` entries in Brewfiles are auto-skipped.
- A recent side effect of this behaviour is that because `brew update` now shows Cask data too, Linux users who cannot make use of Casks see a lot of noise, and may get their hopes up that Casks are available.
- Alternatives to this feature included:
- Putting up with it.
- Skipping outputting `brew update` info for Casks if on Linux.
- Adding `tap "homebrew/cask" if OS.mac?` to my Brewfiles.

Skip tapping homebrew/cask when on Linux

---

lib/bundle/extend/os/linux/skipper.rb

- This `unless` with multiple conditions is hard to understand. This inverts the conditional to make it an `if`.
- As requested in https://github.com/Homebrew/homebrew-bundle/pull/660#discussion_r391892981 and https://github.com/Homebrew/homebrew-bundle/pull/660#discussion_r392193875.

linux/skipper: Refactor `unless` into `if`

---

lib/bundle/mac_app_store_installer.rb
spec/bundle/mac_app_store_installer_spec.rb

@colindean @jacobbednarz I'm not convinced it's a good ROI filing more flaky failure issues. They take a while to debug, they aren't harming end-users and this is not a particularly flaky test suite in general.
Fixes https://github.com/Homebrew/homebrew-bundle/issues/664

mac_app_store_installer: fix flaky test, remove dead code.

---

CONTRIBUTING.md
README.md
cmd/bundle.rb
lib/bundle/brew_installer.rb
lib/bundle/brewfile.rb
lib/bundle/commands/exec.rb

Using colons before subcommand descriptions causes the man page output to indent them. Homebrew/brew#7393 applies the same effect to its `--help` output. This also cleans up the README prose.

cmd/bundle: fixes for help and docs

---

spec/bundle/commands/cleanup_command_spec.rb

Needed for https://github.com/Homebrew/brew/pull/7475

cleanup_command_spec: remove empty before block.

---

README.md

It redirected as expected but it's cleaner to use the correct URL.

Updates link to mas-cli

---

README.md
cmd/bundle.rb

This is included in `brew man`, `brew bundle --help` and is less likely to get outdated as a result.

README: move documentation to --help.

---

lib/bundle/commands/exec.rb
spec/stub/formula.rb

Fixes a deprecation warning in `brew bundle exec`:
```
Warning: Calling Formula#installed? is deprecated! Use Formula#latest_version_installed? (or Formula#any_version_installed? ) instead.
Please report this issue to the homebrew/bundle tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/exec.rb:44
```

Exec: remove call to deprecated method

---

CONTRIBUTING.md
README.md

Anywhere we can use `blob/master` we can use `blob/HEAD` instead. This will make life easier if we ever rename our default branch in future (once/if Git and GitHub provides the necessary tooling to do so).

Refer to default branch in links with HEAD

---

.github/workflows/tests.yml
Gemfile
Gemfile.lock
spec/spec_helper.rb

We used to use them and then bailed due to lack of Azure Pipelines support. Looks like they support both Azure and GitHub Actions now and their gem seems significantly better maintained than Coveralls at this point.
See also: https://github.com/Homebrew/brew/pull/7828

Use CodeCov for coverage reporting.

---

cmd/bundle.rb
lib/bundle/brew_installer.rb
lib/bundle/brew_services.rb
lib/bundle/bundle.rb
lib/bundle/cask_installer.rb
lib/bundle/checker.rb
lib/bundle/commands/check.rb
lib/bundle/installer.rb
lib/bundle/mac_app_store_installer.rb
lib/bundle/tap_checker.rb
lib/bundle/tap_installer.rb
lib/bundle/whalebrew_installer.rb
spec/bundle/brew_installer_spec.rb
spec/bundle/brew_services_spec.rb
spec/bundle/cask_installer_spec.rb
spec/bundle/commands/check_command_spec.rb
spec/bundle/commands/cleanup_command_spec.rb
spec/bundle/commands/exec_command_spec.rb
spec/bundle/dsl_spec.rb
spec/bundle/mac_app_store_installer_spec.rb
spec/bundle/tap_installer_spec.rb
spec/bundle/whalebrew_installer_spec.rb
spec/bundle_utils_spec.rb
spec/stub/global.rb

Pass `verbose` instead of using global `Homebrew.args.verbose?`.

Remove remaining global `Homebrew.args`.

---

lib/bundle/locker.rb
spec/bundle/locker_spec.rb

When a formula uses the GitHubGitDownloadStrategy or GitDownloadStrategy (and perhaps others) `brew info --json=v1 --installed` may produce output related to fetching from git (e.g. to retrieve the latest version). This extraneous output breaks the JSON parsing. This PR adds the `--quiet` flag to suppress all non-json output from `brew info`.

fix: use --quiet flag for brew_list_info

---

lib/bundle/brew_dumper.rb
spec/bundle/brew_dumper_spec.rb

This is deprecated in Homebrew/brew and getting disabled soon.

Remove `devel` support

---

lib/bundle/cask_dumper.rb
lib/bundle/cask_installer.rb
lib/bundle/locker.rb
spec/bundle/cask_installer_spec.rb
spec/bundle/locker_spec.rb

- A lot of the separation between Homebrew formulae and casks was deprecated in [Homebrew 2.5.0](https://brew.sh/2020/09/08/homebrew-2.5.0/), released last week. To avoid `brew bundle` showing deprecation warnings to users, update the invocations.
- Fixes #791.

Fix `brew cask` deprecation warnings

---

cmd/bundle.rb

When `--cleanup` is passed `bundle install` will remove any software not
present in the `Brewfile`.
The behavior of running:
```
brew bundle install --cleanup
```
should be equivalent to running:
```
brew bundle install && brew bundle cleanup --force
```
Fixes https://github.com/Homebrew/homebrew-bundle/issues/793

Add `--cleanup` flag to `bundle install`

---

lib/bundle/dsl.rb
lib/bundle/tap_dumper.rb
lib/bundle/tap_installer.rb
spec/bundle/dsl_spec.rb
spec/bundle/tap_dumper_spec.rb
spec/bundle/tap_installer_spec.rb

This is removed from Homebrew/brew so it'll fail hard anyway so let's remove it here too.
While we're here: also ensure the dumped taps are unique (as they might not be if you'd weird and have both homebrew-core and linuxbrew-core tapped like I do).

Remove tap pinning

---

README.md
cmd/bundle.rb

Minor grammar fixes and add to the `cask_args` sample to show the need to convert dashes to underscores when adding `brew cask install` options.

Improvements for documentation

---

cmd/bundle.rb

I was looking for a way to set the `Brewfile` location using an environment variable and didn't see anything in the docs. I went ahead and started to implement it and realized that the functionality was already there and just hadn't been documented!
This PR adds a mention of the `HOMEBREW_BUNDLE_FILE` environment variable to the docs.

Reference HOMEBREW_BUNDLE_FILE in documentation

---

lib/bundle/cask_dumper.rb
spec/bundle/cask_dumper_spec.rb

Follows on #817 and #792 by updating the `brew cask info` commands to
use the new syntax of `brew info --cask` instead.
cc @issyl0

cask_dumper: Replace `brew cask info` for `brew info --cask`

---

lib/bundle/cask_dumper.rb
lib/bundle/locker.rb
spec/bundle/cask_dumper_spec.rb
spec/bundle/locker_spec.rb

Homebrew/brew@311c106 introduced a deprecation for using JSON output
with the v1 format so it's time to bump up to v2.
Looking over the occurrences and their usage, we should be :ok_hand:
```
$ rg -F "json=v1"
lib/bundle/locker.rb
90:        name_bottles = JSON.parse(`brew info --json=v1 --installed --quiet`)
lib/bundle/cask_dumper.rb
29:      cask_info_response = `brew info --cask #{cask_list.join(" ")} --json=v1`
spec/bundle/locker_spec.rb
73:        allow(locker).to receive(:`).with("brew info --json=v1 --installed --quiet").and_return <<~EOS
spec/bundle/cask_dumper_spec.rb
60:          .with("brew info --cask foo --json=v1")
73:          .with("brew info --cask foo --json=v1")
86:          .with("brew info --cask foo bar --json=v1")
```

Swap to `--json=v2`

---

lib/bundle/cask_dumper.rb
spec/bundle/cask_dumper_spec.rb

cask_dumper: handle stable and master Homebrew/brew versions.

---

lib/bundle/cask_dumper.rb

Brew 2.5.12 was released yesterday and does not yet include the `--cask` arg on the info command, causing `brew bundle cleanup --global` for example to fail due to a parsing error on this sub-command.

Update cask dumper to play nice with 2.5.12

---

lib/bundle/cask_dumper.rb
spec/bundle/cask_dumper_spec.rb
spec/stub/global.rb

Now that 2.6.0 has been released, this is no longer needed.

Remove pre-2.6.0 logic.

---

lib/bundle/brew_dumper.rb

Fixes a bug introduced by #834. That PR added the use of an ActiveSupport method (`String#exclude?`), then added a dependency on it in the spec helper but not in the actual code. This led to runtime `undefined method` errors when calling `brew bundle install`.
```
Error: undefined method `exclude?' for "libtermkey":String
Please report this bug:
https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:192:in `block in sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:191:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:191:in `sort!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_dumper.rb:21:in …
```

Brew dumper: add missing dependency

---

lib/bundle/lister.rb
spec/bundle/commands/list_command_spec.rb

Fix `list --whalebrew`

---

lib/bundle/skipper.rb
spec/bundle/skipper_spec.rb

Fix `HOMEBREW_BUNDLE_WHALEBREW_SKIP`

---

lib/bundle/cask_dumper.rb
spec/bundle/cask_dumper_spec.rb
spec/bundle/dumper_spec.rb
spec/stub/cask.rb
spec/stub/cask/cask.rb
spec/stub/cask/caskroom.rb
spec/stub/utils.rb

Originally the cask names were obtained by running `brew list --cask` and parsing the output. Now we're getting the cask with the `Cask::Caskroom.casks` method and stripping out the name.
Fixes #863 
I know @jacobbednarz had some concerns about this feature. It turned out to be a simple change so I just created this pull request.
This is my first time contributing so I might've missed something. I'd be happy to have feedback!

Switch to getting cask names from Cask module

---

lib/bundle/cask_dumper.rb
spec/bundle/cask_dumper_spec.rb
spec/bundle/dumper_spec.rb
spec/stub/cask/cask.rb

When I switched to using `Cask::Caskroom` to get installed casks, I got the full name of the Cask (including the tap name, if any) instead of just the token. This PR should emulate the old behavior.
Fixes #866

Don't get full cask name when dumping casks

---

lib/bundle/cask_dumper.rb
lib/bundle/cask_installer.rb
lib/bundle/commands/cleanup.rb
lib/bundle/dumper.rb
spec/bundle/cask_dumper_spec.rb
spec/bundle/dumper_spec.rb

Fixes #594: fetch any arguments used when installing casks and include them in the `brew bundle dump` output, substituting the current user's home folder path with `~` if present. Also, prepend cask descriptions if `--describe` is passed (fixes #809).

dump: include args and description for casks

---

README.md
lib/bundle/cask_dumper.rb
lib/bundle/cask_installer.rb
spec/bundle/cask_dumper_spec.rb
spec/bundle/cask_installer_spec.rb
spec/bundle/commands/install_command_spec.rb

Allow currently-installed casks with `auto_updates true` or `version :latest` to be upgraded if `greedy: true` is appended to their Brewfile entry. Solves #897.
Also, start using [`explicit_s`](https://github.com/Homebrew/brew/pull/10462) to generate explicit cask config lines.

Add support for greedy cask upgrades 

---

lib/bundle/brew_dumper.rb
lib/bundle/brew_installer.rb
lib/bundle/cask_dumper.rb
lib/bundle/commands/cleanup.rb
lib/bundle/commands/exec.rb
lib/bundle/dumper.rb
lib/bundle/locker.rb
spec/bundle/brew_dumper_spec.rb
spec/bundle/brew_installer_spec.rb
spec/bundle/cask_dumper_spec.rb
spec/bundle/commands/cleanup_command_spec.rb
spec/bundle/dumper_spec.rb
spec/bundle/locker_spec.rb
spec/stub/exceptions.rb
spec/stub/formula.rb
spec/stub/formulary.rb
spec/stub/global.rb
spec/stub/software_spec.rb
spec/stub/tab.rb
spec/stub/utils.rb

This speeds up `brew bundle check` and `brew bundle` considerably on
my machine:
```console
$ hyperfine --warmup=1 "git checkout master; brew bundle check --global" "git checkout bundle_no_shell_hash; brew bundle check --global"
Benchmark #1: git checkout master; brew bundle check --global
Time (mean ± σ):      4.944 s ±  0.258 s    [User: 1.440 s, System: 1.937 s]
Range (min … max):    4.584 s …  5.338 s    10 runs
Benchmark #2: git checkout bundle_no_shell_hash; brew bundle check --global
Time (mean ± σ):      4.500 s ±  0.100 s    [User: 1.136 s, System: 1.440 s]
Range (min … max):    4.385 s …  4.684 s    10 runs
Summary
'git checkout bundle_no_shell_hash; brew bundle check --global' ran
1.10 ± 0.06 times faster than 'git checkout master; brew bundle check --global'
$ hyperfine …
```

Remove more `brew` and `Formula#to_hash` calls

---

lib/bundle/brew_dumper.rb
spec/bundle/brew_dumper_spec.rb
spec/stub/formula.rb

`declared_runtime_dependencies` is a protected method. Not sure how I didn't hit this during testing...
Fixes #905
Fixes #906

Use runtime_dependencies rather than declared_runtime_dependencies

---

lib/bundle/brew_dumper.rb

These can be `nil` for old tabs.
Fixes #908

brew_dumper: handle `nil` runtime_dependencies.

---

spec/bundle/brew_installer_spec.rb
spec/bundle/brew_services_spec.rb
spec/bundle/brewfile_spec.rb
spec/bundle/commands/check_command_spec.rb
spec/bundle/commands/cleanup_command_spec.rb
spec/bundle/commands/list_command_spec.rb
spec/bundle/locker_spec.rb
spec/bundle/mac_app_store_dumper_spec.rb
spec/bundle/tap_dumper_spec.rb
spec/bundle/whalebrew_dumper_spec.rb
spec/bundle/whalebrew_installer_spec.rb
spec/bundle_utils_spec.rb

- This is newly enabled by https://github.com/Homebrew/brew/pull/10658.

rubocop: Fix RSpec/ContextWording offenses

---

lib/bundle/commands/exec.rb
spec/bundle/commands/exec_command_spec.rb

This extends `brew bundle exec` with the ability to run a command which isn't in the path, for example, my use case was running a `./configure` script using the Brewfile magic, but this wasn't supported.
My patch basically just skips the storage of the path to the command in `command_path` as well as the related null if the command has a directory separator in it anywhere, and then uses `exec` as normal.
In effect, this brings it up to acting more like a shell would, meaning you can run a configure script via `brew bundle exec` as `./configure`, but not as `configure`. On the other hand, you can now run something like `brew bundle exec bin/setup`, or pass an absolute path to an executable.
Specs have been added for the three types of paths this should interact with; absolute and relative …

exec: Allow the use of commands not in the PATH

---

lib/bundle/brew_dumper.rb

The current regex expression cannot handle more than 2 items in the message.
```ruby
e.message =~ /\["(.*)", "(.*)"\]/   # = 'topological sort failed: ["python@3.9", "util-linux", "gettext", "libxml2"]'
cycle_first = Regexp.last_match(1)  # = 'python@3.9", "util-linux", "gettext'
cycle_last = Regexp.last_match(2)   # = 'libxml2'
```
```console
$ brew bundle dump 
Error: Formulae dependency graph sorting failed (likely due to a circular dependency):
python@3.9", "util-linux", "gettext: 
libxml2: ["gdbm", "openssl@1.1", "ncurses", "readline", "zlib", "sqlite", "xz", "bzip2", "libffi", "unzip", "python@3.9"]
Please run the following commands and try again:
brew update
brew uninstall --ignore-dependencies --force python@3.9", "util-linux", "gettext libxml2
brew install python@3.9", …
```

brew_dumper: fix topological sort debugging output.

---

.github/workflows/tests.yml
Gemfile
Gemfile.lock
spec/spec_helper.rb

* Adds codecov action at end of test run
* Adds simplecov-cobertura gem
* Remove codecov gem
* No need to require simplecov, at least according to [this][1]
Closes #949 since it obsoletes the need to upgrade the codecov gem
[1]: https://github.com/simplecov-ruby/simplecov#getting-started

Use codecov action instead of gem

---

lib/bundle/mac_app_store_dumper.rb
spec/bundle/mac_app_store_dumper_spec.rb

This fixes parsing with the format used after the merge of https://github.com/mas-cli/mas/pull/339:
emily@yuyuko ~> mas list
1440147259  AdGuard for Safari  (1.9.13)
497799835   Xcode               (12.5)
425424353   The Unarchiver      (4.3.1)
…
Before:
irb(main):002:0> app.match(/\A(?<id>\d+)\s+(?<name>.*)\s+\((?<version>[\d.]*)\)\Z/)
=> #<MatchData "1440147259  AdGuard for Safari  (1.9.13)" id:"1440147259" name:"AdGuard for Safari " version:"1.9.13">
After:
irb(main):003:0> app.match(/\A(?<id>\d+)\s+(?<name>.*?)\s+\((?<version>[\d.]*)\)\Z/)
=> #<MatchData "1440147259  AdGuard for Safari  (1.9.13)" id:"1440147259" name:"AdGuard for Safari" version:"1.9.13">
Fixes #952.

mac_app_store_dumper: match name non-greedily

---

lib/bundle/brew_installer.rb
lib/bundle/brew_services.rb
lib/bundle/cask_installer.rb
lib/bundle/commands/cleanup.rb
lib/bundle/mac_app_store_installer.rb
lib/bundle/tap_installer.rb
lib/bundle/whalebrew_installer.rb
spec/bundle/brew_installer_spec.rb
spec/bundle/brew_services_spec.rb
spec/bundle/cask_installer_spec.rb
spec/bundle/commands/cleanup_command_spec.rb
spec/bundle/mac_app_store_installer_spec.rb
spec/bundle/tap_installer_spec.rb
spec/bundle/whalebrew_installer_spec.rb
spec/stub/global.rb

`brew bundle` fails if `brew` binary is not present in directories present in PATH.
I just run into this issue while trying to execute `brew bundle` freshly after Homebrew installation.

bundle: use HOMEBREW_BREW_FILE

---

lib/bundle/brew_dumper.rb
lib/bundle/extend/os/linux/skipper.rb
lib/bundle/skipper.rb
spec/bundle/brew_dumper_spec.rb
spec/bundle/skipper_spec.rb
spec/spec_helper.rb
spec/stub/hardware.rb
spec/stub/utils/bottles.rb

Otherwise, a working `Brewfile` on Intel is likely to break on Apple Silicon.
When all of homebrew/core is bottled: we may consider enabling this more widely.

Skip unbottled homebrew/core formulae on Apple Silicon

---

lib/bundle/brew_installer.rb
lib/bundle/cask_installer.rb
lib/bundle/installer.rb
lib/bundle/mac_app_store_installer.rb
lib/bundle/tap_installer.rb
lib/bundle/whalebrew_installer.rb
spec/bundle/brew_installer_spec.rb
spec/bundle/cask_installer_spec.rb
spec/bundle/commands/install_command_spec.rb
spec/bundle/mac_app_store_installer_spec.rb
spec/bundle/tap_installer_spec.rb
spec/bundle/whalebrew_installer_spec.rb

When installing the verb (i.e. "installing", "tapping") is output after the installation is complete (rather than before). This means if an installation is taking a long time or frozen completely there's nothing in the (non-verbose) output to indicate which install is taking the time.
Instead, let's add a "preinstall" step before "install" for each installer which identifies whether an installation will be skipped or not. This will block output but is quicker (as it never does the actual installation but will do a network call for e.g. `mas`) and outputs `Using` _after_ the skip check but `Installing` _before_ actually beginning the installation.

Improve non-verbose output

---

lib/bundle/installer.rb
lib/bundle/skipper.rb
lib/bundle/tap_installer.rb
spec/bundle/commands/install_command_spec.rb
spec/bundle/skipper_spec.rb
spec/bundle/tap_installer_spec.rb

If a `tap` fails, then any subsequent commands can grossly misbehave. For example:
```
tap 'example/formula', 'user@git.example.com:example/homebrew-formulas.git'
brew 'example/formula/internal-tool'
```
If `tap` fails, then bundle currently continues and will attempt to tap (and clone) `https://github.com/example/homebrew-formula` to much sad failure.
This PR changes `bundle` to skip any dependent installations when a tap fails. The other stanzas, `brew`, `cask`, `mas`, `whalebrew`, and others are unchanged and do not abort; my rationale is that their failures are isolated and don't impact each other.

Skip dependents if a tap fails

---

lib/bundle/installer.rb

- Assigning `preinstall` to the output of `puts` meant that it was `nil` when we used it in `cls.install`, which did not equal `true` in the `cls.install` method when we tried to use it (but as it was provided, it was not overridden by the default value `true`).  This makes sure that in the success case (when `cls.preinstall` succeeds, we print a green message), `preinstall` is true and in the inverse case preinstall is negative.
- This meant that while we printed "Installing", nothing was actually installed because `preinstall` was `nil` which is falsey, so we never called `install_change_state!` to do the actual installation.
- My first attempt at fixing this problem was the wrong approach, even though it technically fixed the problem. 😴
- Before:
```
$ brew bundle …
```

lib/bundle/installer: Set `preinstall` variable to `true`/`false`

---

.github/workflows/tests.yml

- In light of 79441868a6a2e1002d8e080c8045483c41b411e3, to avoid future regressions, I was inspired by the `brew services start` tests in [the`brew services` repo](https://github.com/Homebrew/homebrew-services/blob/master/.github/workflows/tests.yml) to make a very simple functional test that this actually installs what it says it does.

workflows/tests: Test that `bundle`ing and running some software works

---

lib/bundle/installer.rb

Currently `brew bundle` logs upgrading formulae as `Installing <formula/cask>`.
This commit changes the verbiage to `Upgrading <fomula/cask>` when the Installer class method `{formula,cask}_upgradable?()` returns `true`

installer.rb: change verb to "Upgrading" on upgradable formula/cask

---

lib/bundle/bundle.rb

Fixes https://github.com/Homebrew/homebrew-bundle/issues/1015
`Bundle::cask_installed?` now returns `true` even if the `homebrew/cask` directory doesn't exist as long as `HOMEBREW_INSTALL_FROM_API` is set.

`bundle`: fix `cask_installed?` with `HOMEBREW_INSTALL_FROM_API` set

---

lib/bundle/mac_app_store_installer.rb
spec/bundle/mac_app_store_installer_spec.rb

`mas` is not yet functional on Monterey. To track progress or to *contribute* to fixing this issue, please see: https://github.com/mas-cli/mas/issues/417

mac_app_store_installer: handle Monterey.

---

lib/bundle/bundle.rb
lib/bundle/mac_app_store_installer.rb
spec/bundle/mac_app_store_installer_spec.rb

As of macOS 12 Monterey, `mas-cli` is no longer able to query whether the user is signed into the App Store.
https://github.com/mas-cli/mas/issues/417
I propose that instead of querying `mas account`, `brew bundle` directly attempts the `mas install` operation it intends to perform. If the user is not yet signed into the App Store, the App Store app appears with a prompt to sign in. This should continue to address the concerns expressed in #233/#235 by @ffittschen.
I also reverted #1019 per my comments [here](https://github.com/Homebrew/homebrew-bundle/pull/1019#issuecomment-961501752).
FYI @phatblat

Remove `mas account` check

---

lib/bundle/skipper.rb
spec/stub/global.rb

It doesn't make sense to do this when we expect to build bottles from source. Now that we've merged homebrew/core and linuxbrew/core, though, ARM and Linux are in the same boat so have this functionality for both.
Fixes #1028

skipper: skip unbottled only on ARM/Linux default prefix.

---

lib/bundle/brew_services.rb

I noticed that running `brew bundle dump` added the `restart_service: true` option for a few formulae that I had installed. I looked into it a bit more and found that this is set for all services with a status that is not `stopped`. I had a few services that I didn't think should be running, but had the status `none` rather than `stopped`. So, they were being given the `restart_service` parameter even though they were stopped and, in my opinion, shouldn't be restarted.
Here's what I did to troubleshoot:
1. `brew install mosquitto`
2. `brew services start mosquitto`
3. `brew services stop mosquitto`
4. `brew services list`
I poked around a bit in the services repository and it looks like the reason the status is showing as `stopped` instead of `none` is that the service isn't "loaded" …

Don't try to restart services with status `none`

---

README.md
lib/bundle/dsl.rb
lib/bundle/tap_installer.rb
spec/bundle/dsl_spec.rb
spec/bundle/tap_installer_spec.rb

Fixes #1063. Allows arguments to taps in a Brewfile with:
tap "foo/bar", "https://host/path/to/tap", args: ["force-auto-update"]
Mostly useful for adding --force-auto-update for non-Github taps.
Syntax is an array of arguments, like with `brew`, rather than a
dictionary like `cask` - this is because none of the optional arguments
of `brew tap` take a value right now. In the future, we should be able
to add support for dictionaries as well without needing to change the
format, if that becomes necessary.

Add support for arbitrary args to tap

---

lib/bundle/brew_installer.rb

I'm setting up a Brewfile that will install the dependencies for a package that is in Homebrew but we're needing to install the package itself outside of Homebrew. I added `args: ['only-dependencies']` to the brew line but it wasn't working: the package itself was getting installed. So, I added this logging facility and realized that I'd typed "only_dependencies" instead. It seems prudent to show all args passed to `brew install` when verbosity is requested.

Emit brew install args when in verbose mode

---

lib/bundle/locker.rb

Currently, the Brewfile.lock.json is always deleted prior to being written to. However, this is breaking for workflows where the Brewfile.lock.json is symlinked into the same directory as the Brewfile, as the symlink is deleted, then a regular file is written in its place. As a result, the file that the symlink references is not updated with the new version info.
This workflow probably isn't super common, but for users of `stow` (https://github.com/aspiers/stow), this might be a nice improvement. They would keep the `.Brewfile` and `.Brewfile.lock.json` in their (e.g.) `~/dotfiles/brew/` folder, and symlink both `.Brewfile` and `.Brewfile.lock.json` to the `~` directory. When running `brew bundle install --global`, it would read from the `.Brewfile` symlinked to `~/.Brewfile`, and write …

only remove lockfile if it is not symlink

---

spec/bundle/locker_spec.rb

Otherwise we're not sufficiently always testing cask version logic.

locker_spec: force cask to be installed.

---

.github/workflows/tests.yml

This PR adds minimum token permissions for the GITHUB_TOKEN using https://github.com/step-security/secure-workflows.
GitHub recommends defining minimum GITHUB_TOKEN permissions for securing GitHub Actions workflows 
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/  
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) treats not setting token permissions as a high-risk issue 
This project is part of the top 100 critical projects as per OpenSSF (https://github.com/ossf/wg-securing-critical-projects), so fixing the token permissions to improve security.
Signed-off-by: Varun …

ci: Add GitHub token permissions for workflows

---

lib/bundle/commands/cleanup.rb

#1099 surfaced a UX improvement that directly tells the user what's going on and what action to take since the default is safety-on.

Instruct user that cleanup without --force takes no action

---

lib/bundle/brew_services.rb
spec/bundle/brew_dumper_spec.rb
spec/bundle/brew_services_spec.rb
spec/stub/utils/popen.rb

`brew` probably isn't in `PATH` here. While we're here, let's avoid the
backticks.
Fixes Homebrew/brew#13611.

brew_services: use `HOMEBREW_BREW_FILE`

---

lib/bundle/brew_dumper.rb
spec/bundle/brew_dumper_spec.rb
spec/bundle/skipper_spec.rb
spec/stub/formula.rb

Bottles are never present on `head` so don't look there, even if that's what's been installed.
Fixes #1117
Closes #1118

brew_dumper: check for bottles on stable spec.

---

lib/bundle/bundle.rb

Add the formula to the `PATH` if not already present.
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1112

bundle: try harder to find mas/whalebrew.

---

.github/workflows/tests.yml

Updates CI run `setup-ruby` on all OS versions since macos-12 has 3.0 for default however, we want to target 2.6 (for now).
Swaps the unmaintained `actions/setup-ruby` for `ruby/setup-ruby` actions while I'm here.

run `setup-ruby` for all OS variants

---

lib/bundle/locker.rb
spec/stub/env_config.rb

- Fixes https://github.com/Homebrew/homebrew-bundle/issues/1170.
- Fixes https://github.com/Homebrew/homebrew-bundle/issues/1169.
- Before, the lockfile would try to populate with `CoreTap.instance.git_head` which doesn't exist when using the API (now the default), leading to this error for the user:
```
> brew bundle --file=testBrewfile
Using asdf
Error: No available tap homebrew/core.
```
Now:
```
> brew bundle --file=testBrewfile
Using asdf
Homebrew Bundle complete! 1 Brewfile dependency now installed.
❯ tail testBrewfile.lock.json
"HOMEBREW_VERSION": "4.0.1-60-gf0bcef6-dirty",
"HOMEBREW_PREFIX": "/opt/homebrew",
"Homebrew/homebrew-core": "api",
"CLT": "14.1.0.0.1.1666437224",
"Xcode": "14.1",
"macOS": "13.0"
}
}
}
}
```

locker: Only get `CoreTap.instance.git_head` if not using the API

---

lib/bundle/locker.rb

I noticed that `linuxbrew-core` was still used here incorrectly so have updated both macOS and Linux methods to share most attributes.

bundle/locker: provide shared system method.

---

lib/bundle/locker.rb
spec/bundle/locker_spec.rb
spec/stub/development_tools.rb

Noticed this TODO while reading through for another task.
And just noticed #1173...
Closes #1173

Drops conditional usage of removed DevelopmentTools.gcc_version

---

lib/bundle/bundle.rb
lib/bundle/locker.rb
spec/stub/env_config.rb

This is private API really. https://github.com/Homebrew/brew/pull/14794 is deleting `install_from_api?` but I noticed this repo was already using it.

Use `no_install_from_api?` to check for API

---

lib/bundle/brew_dumper.rb
spec/bundle/commands/cleanup_command_spec.rb

- Part of https://github.com/Homebrew/brew/pull/14944.
- This stands for "formula".

rubocop: Fix `Naming/MethodParameterName` offenses for "f" name

---

lib/bundle/commands/cleanup.rb
spec/bundle/commands/cleanup_command_spec.rb

Don't uninstall all `vscode` extensions in this case.
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1209

cleanup: graceful migration from `Brewfile` with no `vscode`.

---

lib/bundle/mac_app_store_installer.rb
spec/bundle/mac_app_store_installer_spec.rb

Until `mas outdated` is fixed, we can't trust its output. We're waiting on https://github.com/mas-cli/mas/pull/496 to be merged upstream and then this can be reverted.

mac_app_store_installer: workaround `mas outdated` bug.

---

lib/bundle/bundle.rb
spec/bundle_utils_spec.rb
spec/stub/global.rb

It's semantically more correct and also what's used [throughout](https://github.com/Homebrew/brew/blob/1f80e82dd72fce6642e4ea360f7a1feef5d78470/Library/Homebrew/brew.sh#L492) [brew](https://github.com/Homebrew/brew/blob/1f80e82dd72fce6642e4ea360f7a1feef5d78470/Library/Homebrew/cmd/update.sh#L581) (`$HOMEBREW_LIBRARY/Taps/*/*` for taps, `$HOMEBREW_REPOSITORY` for updating brew itself).

bundle: Check for cask tap using HOMEBREW_LIBRARY

---

cmd/bundle.rb
lib/bundle/brew_installer.rb
lib/bundle/cask_dumper.rb
lib/bundle/cask_installer.rb
lib/bundle/commands/install.rb
lib/bundle/installer.rb
lib/bundle/mac_app_store_installer.rb
lib/bundle/tap_installer.rb
lib/bundle/vscode_extension_installer.rb
lib/bundle/whalebrew_installer.rb

Allows passing `brew bundle --force` to make installed formulae run `brew install --formula --force --overwrite` and casks `brew install --cask --force` when installed.
This is useful in environments where it's common for casks to need to be overwritten.

Make `--force` take effect on install.

---

cmd/bundle.rb

This should only automatically cleanup when `--global` is passed otherwise you risk uninstalling (much) more that intended.

cmd/bundle: tweak HOMEBREW_BUNDLE_INSTALL_CLEANUP behaviour.

---

lib/bundle/brew_installer.rb

If we run `brew bundle install --force`: we should also run `brew link --force` to be consistent.

brew_installer: run `brew link --force` when requested.

---

lib/bundle/tap_dumper.rb
spec/bundle/tap_dumper_spec.rb

If it's present in a tap's git remote: filter it out and replace it with a lookup for the environment variable instead.

tap_dumper: filter HOMEBREW_GITHUB_API_TOKEN.

---

.github/workflows/tests.yml
lib/bundle/bundle.rb

Now that Homebrew 4.2.0 runs on Ruby 3.1, let's bump to that.
https://brew.sh/2023/12/18/homebrew-4.2.0/

Run tests on Ruby 3.1

---

lib/bundle/brew_dumper.rb
lib/bundle/brew_installer.rb

These incorrect end up turning `false` into `true`.
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1274

Fix some usage of `!foo.nil?`

---

README.md

This has broken CI on other PRs.
Might want to change the `id:` handling but that can happen after we fix dependabot first.

README: fix `brew style`.

---

lib/bundle/vscode_extension_dumper.rb

VSCode seems to be doing this itself in newer versions so this will allow for some more consistency.
Fixes #1302

vscode_extension_dumper: downcase extension names.

---

lib/bundle/commands/cleanup.rb
lib/bundle/vscode_extension_dumper.rb
lib/bundle/vscode_extension_installer.rb
spec/bundle/commands/cleanup_command_spec.rb
spec/bundle/vscode_extension_installer_spec.rb

fixes #1302 in a consistent manner such that cleanup doesn't uninstall if the case mismatch occurs

vscode_extension cleanup: downcase extension names before comparison while evaluating for cleanup

---

spec/bundle/commands/dump_command_spec.rb
spec/bundle/dumper_spec.rb

I have an env var setup to point to the global `Brewfile`. If this is set, and following the contribution guidelines for this repo, then the tests fail. To circumvent that failure, this change in tests is required.

fix tests if the user has a HOMEBREW_BUNDLE_FILE env var setup

---

cmd/bundle.rb

Some minor formatting & wording fixes for the manpage.

manpage: minor formatting & wording fixes

---

lib/bundle/cask_dumper.rb
lib/bundle/cask_installer.rb
spec/bundle/cask_dumper_spec.rb
spec/bundle/cask_installer_spec.rb
spec/stub/cask/cask.rb

In some instances, calling `.outdated?(greedy: true)` causes additional network requests. (casks using `version :latest` and `sha256 :no_check` seem to trigger this)
Currently, this is done for *all installed packages* every time `brew bundle` wants to update *any* cask greedily.
This pull request changes `bundle`'s behavior to only check whether one cask is outdated at a time (for greedy updates).

Don’t prefetch greedy outdated casks

---

lib/bundle/brew_checker.rb
lib/bundle/brew_dumper.rb
lib/bundle/brew_installer.rb
lib/bundle/brewfile.rb
lib/bundle/cask_checker.rb
lib/bundle/cask_installer.rb
lib/bundle/checker.rb
lib/bundle/commands/check.rb
lib/bundle/commands/cleanup.rb
lib/bundle/commands/dump.rb
lib/bundle/commands/exec.rb
lib/bundle/commands/install.rb
lib/bundle/commands/list.rb
lib/bundle/dsl.rb
lib/bundle/dumper.rb
lib/bundle/installer.rb
lib/bundle/lister.rb
lib/bundle/locker.rb
lib/bundle/mac_app_store_checker.rb
lib/bundle/mac_app_store_installer.rb
lib/bundle/tap_installer.rb
lib/bundle/vscode_extension_installer.rb
lib/bundle/whalebrew_installer.rb
spec/bundle/brew_dumper_spec.rb
spec/bundle/brew_installer_spec.rb
spec/bundle/brewfile_spec.rb
spec/bundle/commands/check_command_spec.rb

For https://github.com/Homebrew/brew/pull/16848

Use RuboCop default hash syntax.

---

spec/bundle/vscode_extension_installer_spec.rb

Replace references to 'apps' and 'mas' with the VSCode appropriate terms.

Fix references to VSCode in extension installer test

---

lib/bundle/vscode_extension_installer.rb
spec/bundle/vscode_extension_installer_spec.rb
spec/stub/extend/kernel.rb

This should make sense in the general case. VSCode should always install based on the calling user rather than the middle man.

vscode_extension_installer: use UID for installs

---

lib/bundle/brew_services.rb
lib/bundle/bundle.rb
lib/bundle/vscode_extension_dumper.rb
lib/bundle/vscode_extension_installer.rb

This requires moving it to `Bundle.exchange_uid` to be used by both `vscode_extension_dumper` and `vscode_extension_installer`.

vscode_extension_dumper: also use exchange_uid.

---

lib/bundle/brewfile.rb
lib/bundle/bundle.rb
lib/bundle/dumper.rb
lib/bundle/locker.rb
lib/bundle/vscode_extension_dumper.rb
lib/bundle/vscode_extension_installer.rb

This is needed basically anywhere we read `$HOME` or write to files as that may be in `$HOME`.
While we're here, change name to `exchange_uid_if_needed!` to make it more obvious that it's only needed in some cases.

bundle: exchange euid/uid in more places as needed.

---

cmd/bundle.rb

See https://github.com/Homebrew/homebrew-services/pull/639
Discovered via https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/cmd/bundle_spec.rb (this should be the last PR of this type, going by `setup_remote_tap` call sites in `brew` tests)

Port bundle command to use AbstractCommand

---

cmd/bundle.rb

This is the version required for `AbstractCommand` to work.
While we're here: remove all the exception handling that duplicates `brew.rb` and isn't present in other taps.

cmd/bundle: note when Homebrew is too old.

---

lib/bundle/commands/cleanup.rb

Otherwise, these may be uninstalled from the wrong user.

bundle/commands/cleanup: exchange UID if needed on VSCode uninstall.

---

cmd/bundle.rb
lib/bundle/commands/install.rb
lib/bundle/installer.rb

This is intended to resolve #1202. Only addresses the `brew bundle install` subcommand because I don't see any other subcommands where `--quiet` makes sense. I don't think it's desirable to suppress other non-error output (e.g. "Homebrew Bundle complete!..." and "Downloading https://formulae.brew.sh/api/cask.jws.json") unless we added a -qq option, which would require more far reaching changes to how arg parsing works (`--quiet` is parsed by code in `homebrew/brew`, not this repo).
Fixes #1202

--quiet silences "Using xyz" in `brew bundle install`

---

cmd/bundle.rb

* Add `named_args` so Homebrew::Completions can discover subcommands
* `raise` an error if `args.named.size > 1`, unless we're running `brew bundle exec`: this fails loudly on some commands that are currently accepted and may appear valid but don't do what you'd expect. Each of the below commands currently execute the first subcommand and ignore the second silently:
* `brew bundle install my_package`
* `brew bundle install cleanup` (not to be confused with `brew bundle install --cleanup`!)
* `brew bundle cleanup install`
* note: cannot use the `max: 1` annotation for named args because this would break `brew bundle exec`
I wrote this commit as part of my abortive effort on zsh completion. Sending the PR anyway, because imo it's still an improvement to usability and will be of some …

enforce limit of one subcommand, list named_args

---

README.md

Maybe this should be obvious, but as a first time committer it took me a few rounds of CI fails before I figured out how to get this check to run locally. I'm not attached to the wording, but this should somehow be more discoverable.

document running linter w/ test-bot

---

lib/bundle/brewfile.rb
lib/bundle/checker.rb
lib/bundle/commands/cleanup.rb
lib/bundle/commands/exec.rb
lib/bundle/commands/install.rb
lib/bundle/commands/list.rb
lib/bundle/dsl.rb
spec/bundle/dsl_spec.rb

`__FILE__` in Brewfiles currently is set to `(eval at ...)`. Given we never read the Brewfile without creating a DSL class, we can simplify things to pass the path and use that in `instance_eval` to set the `__FILE__` to the real path.

Support `__FILE__` in Brewfiles

---

cmd/bundle.rb
lib/bundle/commands/cleanup.rb
lib/bundle/commands/exec.rb
lib/bundle/commands/install.rb
spec/bundle/commands/install_command_spec.rb

This was previously failing to read a valid `Brewfile` on repeated reads so attempting to cleanup everything.
Instead, cache the `Brewfile` DSL in the `install` command and pass it to the `cleanup` command.
While we're here, make some `dsl` usage elsewhere a little more consistent.
Fixes #1378

Fix `brew bundle --cleanup` from `stdin`

---

lib/bundle/tap_installer.rb

I have 
```ruby
tap "homebrew/core"
tap "homebrew/cask"
```
in my Brewfile and since those casks are no longer required, `brew bundle install` will receive and error via calling `brew tap :name`.
Passing `--force` flag in `brew bundle install` has no effect due to `TapInstaller.install()` `force` argument is ignored.

Apply --force flag if set for taps

---

cmd/bundle.rb
lib/bundle/commands/cleanup.rb
spec/bundle/commands/cleanup_command_spec.rb

Closes #1418 
The exception is for `brew cleanup` action, since it's just an extra step that's
not really related to the Brewfile contents.
I think this also fixes an issue where `vscode` uninstalls would not have printed the `--force` message — now they will also be considered for printing the message and the exit code.

cleanup: exit 1 when any action would have been taken

---

lib/bundle/whalebrew_dumper.rb

I have a few whalebrew packages installed
```bash
$ whalebrew list
COMMAND          IMAGE
figlet           whalebrew/figlet
graph-easy       nathanielvarona/graph-easy
octodns-compare  whalebrew/octodns-compare
whalesay         whalebrew/whalesay
```
However, if I use the Bundle Dump from Homebrew, the results look like:
```bash
whalebrew "whalebrew/figlet"
whalebrew "graph-nathanielvarona/graph-easy"
whalebrew "octodns-whalebrew/octodns-compare"
whalebrew "whalebrew/whalesay"
```
The expected output supposedly:
```bash
whalebrew "whalebrew/figlet"
whalebrew "nathanielvarona/graph-easy"
whalebrew "whalebrew/octodns-compare"
whalebrew "whalebrew/whalesay"
```
I created the PR to fix this issue of dumping the packages list from Whalebrew.
With the fixes, running the `brew bundle dump …

bundle dump: fix whalebrew dump output

---

lib/bundle/commands/exec.rb
spec/bundle/commands/exec_command_spec.rb

If `nodenv`, `pyenv`, or `rbenv` are in the `Brewfile`, let's add their
`shims` directory to `PATH` during `brew bundle exec`.
This makes it so that `brew bundle exec` just works without relying on
the user adding the required `node`/`python3`/`ruby` formula to their
`Brewfile` and then doing `brew *env-sync`.

exec: support `nodenv`, `pyenv` and `rbenv`

---

lib/bundle/brew_installer.rb

Fixes passing `brew bundle --force` to:
- make formula installation run `brew install <formula> --force --overwrite`
- run `brew link --overwrite <formula>` to force relinking of an unlinked non-keg by default (i.e. `link: nil`)
Previously =>
> $ brew bundle --force  --verbose
> $ Installing gnupg formula. It is not currently installed.
Now =>
> $ brew bundle --force  --verbose
> $ Installing gnupg formula with --force --overwrite. It is not currently installed.

brew_installer: fix use of force flag

---

cmd/bundle.rb
lib/bundle/commands/dump.rb
lib/bundle/commands/list.rb
lib/bundle/dumper.rb
lib/bundle/lister.rb
spec/bundle/commands/dump_command_spec.rb
spec/bundle/commands/exec_command_spec.rb
spec/bundle/commands/list_command_spec.rb
spec/bundle/dumper_spec.rb

This allows excluding VSCode output from `brew bundle dump` with a flag or environment variable.
While we're here
- generally refactor how we handle command arguments so this logic is pushed into `cmd/bundle` and made more consistent
- fix early RSpec failure due to an unstubbed `exec` call
- refactor some specs to be more idiomatic
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1209
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1212
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1456

Add --no-vscode and HOMEBREW_BUNDLE_DUMP_NO_VSCODE

---

lib/bundle/bundle.rb
lib/bundle/mac_app_store_installer.rb
spec/bundle/mac_app_store_installer_spec.rb

- Once the next version of `mas` is released: we can again rely on `mas outdated`.
- `mas_signedin?` hasn't worked for a long time and isn't coming back so just delete the code to simplify things.

mas v1.8.7 updates

---

lib/bundle/commands/cleanup.rb
spec/bundle/commands/cleanup_command_spec.rb
spec/stub/formula.rb

I have a Brewfile that contains the following line:
```ruby
brew "heroku/brew/heroku"
```
Running `brew bundle cleanup --verbose` includes the following output:
```
Would untap:
heroku/brew
```
However, this tap can't be removed as the fomula depends on it.
Considering you can install formulae without explicitly adding a `tap` declaration, it seems that these should be respected when computing which taps to keep.
This change does that: Any tap found in a `brew` declaration will automatically be kept.

Keep implicit taps

---

lib/bundle/commands/cleanup.rb
spec/bundle/commands/cleanup_command_spec.rb
spec/stub/exceptions.rb

This addresses an issue in #1495.
I set up a new machine and ran `brew bundle cleanup --verbose` which then exited with the following error:
```
Error: No available formula with the name "heroku/brew/heroku".
Please tap it and then try again: brew tap heroku/brew
```
This is because I hadn't installed anything and therefore `Formulary.factory` couldn't find the formula.
With this change, I'm making an assumption that if we can't find the formula, we don't need to keep its associated tap and therefore it's fine to ignore the exception and consequently not include the tap in `kept_taps`.
~I would like to add a test case but `TapFormulaUnavailableError` isn't available and wasn't sure it was desired to define it for testing. Let me know if I should.~ I found …

Ignore taps of unavailable formulae

---

lib/bundle/brew_installer.rb

---
9dfc103 fix(install): use full names for linked and keg_only checks
Minimal repro:
```console
❯ brew bundle --file - <<<'tap "gibfahn/tap", "https://github.com/gibfahn/homebrew-tap"
tap "gibfahn/tap2", "https://github.com/gibfahn/homebrew-tap"
brew "gibfahn/tap/check-sieve"'
Using gibfahn/tap
Using gibfahn/tap2
Using gibfahn/tap/check-sieve
Error: Formulae found in multiple taps:
* gibfahn/tap/check-sieve
* gibfahn/tap2/check-sieve
Please use the fully-qualified name (e.g. gibfahn/tap/check-sieve) to refer to a specific formula.
```
If you run with `HOMEBREW_DEBUG=1` you can see that the cause of this is
using the `@name` rather than the `@full_name` in the checks run after
the installation is complete.
<br/>

Use full names for linked and keg_only checks

---

lib/bundle/brew_installer.rb
lib/bundle/brew_services.rb
lib/bundle/bundle.rb
lib/bundle/cask_installer.rb
lib/bundle/mac_app_store_installer.rb
lib/bundle/tap_installer.rb
lib/bundle/vscode_extension_installer.rb
lib/bundle/whalebrew_installer.rb

Add a `Bundle.brew` helper to DRY things up a bit.

Improve shelling out to `brew`

---

spec/bundle/commands/check_command_spec.rbi
spec/stub/formulary.rb

- Add an RBI for a dynamically defined class
- Make `Formulary` a `module` like in Homebrew/brew

Fix some `brew typecheck homebrew/bundle` cases

---

cmd/bundle.rb
cmd/bundle.rbi

- Part of https://github.com/Homebrew/brew/issues/17297.

Bump `cmd`s to Sorbet `typed: strict`

---

README.md
lib/bundle/brew_dumper.rb
lib/bundle/brew_installer.rb
lib/bundle/cask_installer.rb
spec/bundle/brew_installer_spec.rb
spec/bundle/cask_installer_spec.rb

This allows `postinstall` to be used to run a command after a formula or cask is installed.
While we're here, also adjust the `restart_service` behaviour to correctly match the comment i.e. require `always` to restart every time and otherwise just restart on an install or upgrade of a formula.

Add `postinstall` support for `brew` and `cask`

---

cmd/bundle.rb

This is already a `--no-upgrade` argument but let's add it as an environment variable for easier configuration.
While we're here, let's also correct the comment to note that it also affects `brew bundle check`.

cmd/bundle: add HOMEBREW_BUNDLE_NO_UPGRADE.

---

lib/bundle/commands/exec.rb

This (somewhat) makes sense when building formulae but doesn't make sense for `brew bundle exec`. The list should be fairly minimal and reflect actual project dependencies from the `Brewfile` rather than all recursive ones.

commands/exec: don't use recursive deps.

---

lib/bundle/brew_installer.rb

If a user supplies `link: false` in their `Brewfile` then let's also pass `--skip-link` to `brew install`.
Depends on https://github.com/Homebrew/brew/pull/19136

brew_installer: use --skip-link.

---

lib/bundle/commands/exec.rb
spec/bundle/commands/exec_command_spec.rb

Provide `HOMEBREW_BUNDLE_EXEC_ALL_KEG_ONLY_DEPS` and `HOMEBREW_BUNDLE_EXEC_FORMULA_VERSION_*` variables to allow adjusting the environment variables that are set in `brew bundle exec`.

commands/exec: allow customising environment.

---

cmd/bundle.rb
cmd/bundle.rbi

This allows overriding the `HOMEBREW_BUNDLE_NO_UPGRADE` environment variable. The environment variable wasn't really documented specifically before so let's do that here, too.
Also, add `brew bundle upgrade` for a shorthand version.

bundle: add upgrade switch and command.

---

cmd/bundle.rb

These are (mostly) shorthands for `brew bundle exec sh` and `brew bundle exec env` that provide `brew`-like shell and environment features on top of `brew bundle exec`.

cmd/bundle: add `brew bundle sh` and `brew bundle env` helper commands.

---

cmd/bundle.rb

This is shorthand for `brew edit <Brewfile path>`.

cmd/bundle: add `brew bundle edit` command.

---

cmd/bundle.rb
lib/bundle/brewfile.rb
spec/bundle/brewfile_spec.rb

Indirectly support XDG_CONFIG_HOME by leaning on `brew`'s support for it. 
when `--global` is set, we'll get the brewfile from:
- $HOMEBREW_BUNDLE_FILE_GLOBAL if set
- $XDG_CONFIG_HOME/homebrew/Brewfile (if XDG_CONFIG_HOME is set and file exists)
- $HOME/.homebrew/Brewfile (if XDG_CONFIG_HOME _is not_ set, and file exists)
- ~/.Brewfile (unconditional fallback, ~but if this doesn't exist either, we should probably use $HOMEBREW_USER_CONFIG_HOME/Brewfile as the new default~ [edit: per feedback])
Starting this as a draft because:
- looking for feedback on whether this change is welcome at all (I suspect so, per: https://github.com/Homebrew/homebrew-bundle/issues/1002#issuecomment-917613646)
- looking for feedback on what the fallback default should be if no file exists
- I still need to add …

look for Brewfile in HOMEBREW_USER_CONFIG_HOME

---

cmd/bundle.rb

- address [@rrotter's comment](https://github.com/Homebrew/homebrew-bundle/pull/1549#issuecomment-2615288351) by referencing `XDG_CONFIG_HOME` rather than `HOMEBREW_USER_CONFIG_HOME` (and internal variable).
- use environment variable names consistently.

cmd/bundle: improve documentation consistency.

---

cmd/bundle.rb

Partial revert of https://github.com/Homebrew/homebrew-bundle/pull/1579
See https://github.com/Homebrew/brew/pull/19153#discussion_r1930678587

cmd/bundle: use `~` instead of `${HOME}`

---

lib/bundle/brew_installer.rb
lib/bundle/cask_installer.rb
spec/bundle/brew_installer_spec.rb
spec/bundle/cask_installer_spec.rb

This wasn't working as expected for multiple argument `postinstall`s unless in verbose mode so let's just use `Kernel.system` directly (which verbose mode was doing anyway and we already use in a few places).
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1594

{brew,cask}_installer: fix non-verbose postinstall.

---

lib/bundle/cask_installer.rb
spec/bundle/cask_installer_spec.rb

This makes more sense as a default for Homebrew/bundle (and maybe even Homebrew) because it avoids errors that require manual intervention to end up with the same result.

cask_installer: use `--adopt` if `--force` is not provided.

---

lib/bundle/extend/os/linux/bundle.rb

Adds cask dump support to Linux, by removing the default cask_installed? return. Fixes part of #1620.

fix(bundle): dump installed casks on Linux

---

cmd/bundle.rb

Fixes #1635
- Update `--file` option description to indicate that Brewfiles can be both read from and written to.
- Improve `brew bundle dump` documentation to mention custom file support via `--file`.
This PR makes it easy for folks to discover that they can do something like `brew bundle dump --file="/tmp/Brewfile"`.

bundle dump: Clarify `--file` usage for reading and writing

---

lib/bundle/commands/exec.rb

Cleanup Homebrew's global environment variables that we don't want to leak into the `brew bundle exec` environment.
Follow-up from https://github.com/Homebrew/brew/pull/19421 cleaning up the variables that aren't/can't be removed there.

commands/exec: cleanup Homebrew's global environment

---

cmd/bundle.rb
lib/bundle/commands/install.rb
lib/bundle/installer.rb

Use `$stderr` for `brew bundle env --install` output that we don't want to be e.g. `eval`ed.

Improve `brew bundle env --install` output

---

cmd/bundle.rb
lib/bundle/commands/exec.rb
spec/bundle/commands/exec_command_spec.rb
spec/stub/extend/ENV.rb

Ensure brew bundle sh/env commands have access to other tools in the PATH.

Improve brew bundle env/sh PATH

---

cmd/bundle.rb

Add help text for `add` and `remove`

---

lib/bundle/commands/exec.rb

This was always writing to `PATH` instead of the actual variable.

commands/exec: fix PATH-like variable handling.
