.travis.yml
This PR didn't change too much at the moment but should be helpful for future development.
=> Make CI work in OS X with homebrew installed

cmd/brew-brewdle.rb, lib/brewdler/dsl.rb, lib/brewdler/utils.rb, spec/system_spec.rb
=> show the install result and add verbose option

lib/brewdler/commands/cleanup.rb, lib/brewdler/commands/install.rb, lib/brewdler/dsl.rb, spec/dsl_spec.rb, spec/install_command_spec.rb, spec/security_spec.rb
1. Remove the legacy code (#57).
2. Call `process` inside `initialize` for Dsl.
3. Improve the error message.
=> Code Refactor

lib/bundle/commands/install.rb, lib/bundle/dsl.rb
=> dsl: exit 1 when there are failures.

lib/bundle/cask_installer.rb, spec/caskinstaller_spec.rb
=> Skip installed cask

lib/bundle/brew_dumper.rb, lib/bundle/commands/cleanup.rb, spec/brewdumper_spec.rb, spec/cleanup_command_spec.rb
=> Dump full tap paths 

.travis.yml, lib/bundle/brew_dumper.rb, lib/bundle/cask_dumper.rb, lib/bundle/dumper.rb, spec/brewdumper_spec.rb, spec/caskdumper_spec.rb
Fixes #74.
Requires https://github.com/Homebrew/homebrew/pull/40451 merged first.
=> Dump: sorted by dependant order

cmd/brew-bundle.rb
=> check homebrew revision against minimum requirement

.travis.yml, cmd/brew-brewdle, cmd/brew-brewdle.rb, cmd/brew-brewdler, cmd/brew-brewdler.rb, cmd/brew-bundle, cmd/brew-bundler, cmd/brew-bundler.rb
=> drop support for ruby 1.x

cmd/brew-bundle, lib/bundle/dsl.rb
Fixes #92, #95.
cc @mikemcquaid
=> improve error message

lib/bundle/cask_dumper.rb, lib/bundle/cask_installer.rb
=> Don't warn on empty `brew cask list`.

Readme.md, lib/bundle/cask_installer.rb, lib/bundle/dsl.rb, spec/caskinstaller_spec.rb, spec/dsl_spec.rb
Combines and squashes @Liquidsoul and @joshuairl's work in #94 and #115 with some test improvements. Would have pushed straight to `master` but we've enabled protected branches.
=> Cask args final

.gitignore, cmd/brew-bundle, lib/bundle/brew_dumper.rb, lib/bundle/brew_installer.rb, lib/bundle/brew_services.rb, lib/bundle/cask_dumper.rb, lib/bundle/cask_installer.rb, lib/bundle/commands/check.rb, lib/bundle/commands/cleanup.rb, lib/bundle/commands/dump.rb, lib/bundle/dsl.rb, lib/bundle/dumper.rb, lib/bundle/tap_dumper.rb, lib/bundle/tap_installer.rb, lib/bundle/utils.rb, spec/brewdumper_spec.rb, spec/brewinstaller_spec.rb, spec/caskdumper_spec.rb, spec/check_command_spec.rb, spec/cleanup_command_spec.rb, spec/dsl_spec.rb, spec/dumper_spec.rb, spec/tapdumper_spec.rb, spec/tapinstaller_spec.rb
* Use singleton(`Class.method`) instead of object(`Class.new.method`).
* Handle case when using alias to refer tap formula, i.e. `foo/bar/alias -> foo/bar/baz` or `alias -> foo/bar/baz`
* Improve test case.
* Sanitize input name in DSL.
* Update minimum Homebrew version.
=> Use singleton

lib/bundle/brew_installer.rb, lib/bundle/cask_installer.rb, lib/bundle/commands/cleanup.rb, lib/bundle/tap_installer.rb, spec/brew_dumper_spec.rb, spec/brew_installer_spec.rb, spec/cask_installer_spec.rb, spec/dsl_spec.rb, spec/spec_helper.rb
Generated by running command
` brew style --fix **/*.rb`
=> fix code style

lib/bundle/dsl.rb, spec/dsl_spec.rb
=> dsl: check arguments' type

lib/bundle/brew_installer.rb, spec/brew_installer_spec.rb
=> Don't unconditionally return false when checking for upgradability

lib/bundle/brew_installer.rb, lib/bundle/brew_services.rb, spec/brew_installer_spec.rb, spec/brew_services_spec.rb
Address @xu-cheng's comments from after https://github.com/Homebrew/homebrew-bundle/pull/154 was merged.
=> Improve style of `conflicts_with` implementation.

lib/bundle/commands/cleanup.rb, spec/cleanup_command_spec.rb
Do NOT try to cleanup homebrew/core and homebrew/bundle
=> cleanup: ignore certain taps

lib/bundle/brew_dumper.rb, lib/bundle/brew_services.rb
Mon Aug  8 20:15:27 BST 2016
This pull request is in response to #192. 
As this is my first dive-into-ruby,  would appreciate guidance WRT writing tests (to comply with the ```guidelines for contributing```.
=> Add restart_service: true to Brewfile on full dump

Readme.md
=> Minor grammar fix in README

Readme.md
=> It's called macOS now.

Readme.md
=> README: general cleanup.

Gemfile, Readme.md, spec/spec_helper.rb
This works nicely for Homebrew/brew so let's use it here now too.
=> Use CodeCov instead of Coveralls.

cmd/brew-bundle.rb
This has changed in Homebrew/brew.
=> brew-bundle: fix Tty usage.

cmd/brew-bundle.rb
Use Homebrew’s new method of printing out `--help`.
=> brew-bundle: use Homebrew help method.

Gemfile
=> Use HTTPS source in Gemfile

lib/bundle/commands/cleanup.rb, spec/cleanup_command_spec.rb, spec/spec_helper.rb
Fix the deprecations of `puts_columns` and `MultiFormatter[]`.
Fixes #218.
=> Fix deprecations.

spec/spec_helper.rb
Fix merge conflicts in https://github.com/Homebrew/homebrew-bundle/pull/205.
Closes https://github.com/Homebrew/homebrew-bundle/pull/205
=> Tweak Simplecov formatters

cmd/brew-bundle.rb, lib/bundle/brew_installer.rb
As requested for people who want to avoid upgrading.
CC @mislav @jeremy
Fixes #229.
=> Add `--no-upgrade` option.

lib/bundle/brew_dumper.rb, spec/brew_dumper_spec.rb
Previously we weren't correctly removing optional and build dependencies so we could end up with dependencies due to option usage. Arguably formulae authors still have messed up in adding these but we may as well handle these where we can.
When there is a circular dependency error still provide a more helpful error message.
Fixes #241.
Fixes #240.
=> brew_dumper: fix tsort handling.

.travis.yml, lib/bundle/mac_app_store_installer.rb
Use the most consistent Homebrew organisation-wide style soon to be included by default in `brew tap-new`.
=> .travis.yml: use more consistent style.

lib/bundle/brew_installer.rb, lib/bundle/cask_installer.rb, lib/bundle/dsl.rb, lib/bundle/mac_app_store_installer.rb, lib/bundle/tap_installer.rb, spec/brew_installer_spec.rb, spec/cask_installer_spec.rb, spec/install_command_spec.rb, spec/mac_app_store_installer_spec.rb, spec/spec_helper.rb, spec/tap_installer_spec.rb
- Use colours where appropriate
- Note when things weren't actually installed/upgraded etc. but we're just using the version already there
- Improve success/failure messaging
- Generally copy Bundler's (lovely) formatting
CC @mislav and @javierjulio who motivated this PR.
=> Improve Homebrew Bundle output

Gemfile, spec/brew_dumper_spec.rb, spec/brew_installer_spec.rb, spec/spec_helper.rb
As the upstream Homebrew rules were changed.
=> Rubocop style fixes.

lib/bundle/cask_installer.rb, spec/cask_installer_spec.rb
Sometimes you just want to bulldoze over existing packages 😛
=> Allow passing boolean flag args like --force to cask install

lib/bundle/commands/cleanup.rb
Fix the issue that assumed incorrectly that all formulae depend on a single level of dependencies by recursing through all dependencies of each dependency.
=> cleanup: traverse dependencies recursively.

Gemfile, cmd/brew-bundle.rb, lib/bundle/brew_dumper.rb, lib/bundle/bundle.rb, lib/bundle/cask_installer.rb, lib/bundle/commands/cleanup.rb, lib/bundle/commands/exec.rb, spec/brew_services_spec.rb, spec/spec_helper.rb
Using the new rules in Homebrew/brew#2679.
=> Fix RuboCop warnings.

Readme.md
=> README: note no Linuxbrew support.

Readme.md
=> Readme: various updates.

.travis.yml
It's installed already by RVM.
=> travis.yml: don't install bundler.

lib/bundle/dsl.rb, spec/dsl_spec.rb
I apologize in advance for my pedantry
=> Pluralize 'dependency' in bundle output

lib/bundle/brew_dumper.rb, spec/brew_dumper_spec.rb
Dump whether the user has manually linked or unlinked a keg.
=> brew_dumper: dump link status.

CONTRIBUTING.md
Running tests is obvious but the style check step is not.
The style check should probably be added to a rake task…
=> Adds notes about steps before submitting a PR

lib/bundle/brew_dumper.rb, lib/bundle/bundle.rb, spec/spec_helper.rb
Refactor code for a clean RuboCop 0.53.0 run.
=> Rubocop 0.53.0 updates

lib/bundle/bundle.rb, spec/utils_spec.rb
Fixes https://github.com/Homebrew/homebrew-bundle/issues/338.
=> Fix `cask_installed?`.

lib/bundle/brew_dumper.rb, spec/brew_dumper_spec.rb
=> brew_dumper: handle formulae syntax errors.

cmd/brew-bundle.rb, lib/bundle/brew_dumper.rb, lib/bundle/commands/cleanup.rb, spec/stub/extend/ENV.rb
And `NoMethodError` is a type of `NameError`.
=> brew_dumper: NameError makes formulae unreadable.

lib/bundle/brew_dumper.rb, spec/brew_dumper_spec.rb, spec/brew_installer_spec.rb, spec/cleanup_command_spec.rb
Fixes #361
See that issue and maybe the commits for details.
=> Fixes flakey tests

cmd/brew-bundle.rb
Fix a few inconsistencies and append colons to command specs.
=> Update bundle help text

Gemfile, Gemfile.lock, README.md, spec/spec_helper.rb
It's not been working for a while and we're not really using it as we mandate 100% coverage.
=> Remove Codecov

lib/bundle/checker.rb, lib/bundle/mac_app_store_checker.rb
CC @jsatk
Fixes https://github.com/Homebrew/homebrew-bundle/issues/401
=> checker: fix handling `mas`.

lib/bundle/brew_dumper.rb
Ensure that we strip the tap section so they are dumped properly.
=> dumper: fix dumping cask requirements.

README.md
I was looking for what the flag was for this (or whether it was an option at all) and had to read the man pages to figure out. It doesn't show up easily after googling either so I thought it would be helpful to add a note in the readme. Let me know what y'all think it's helpful and whether I should rephrase the note. 
Thanks!
=> add note on `brew bundle --file=path` to README.md

lib/bundle/brew_dumper.rb
=> brew_dumper: improve circular dependency suggestion.

azure-pipelines.yml
Should enable #427 and #428 to proceed
=> Explicitly install bundler and gems before using them

Gemfile.lock, azure-pipelines.yml
This should avoid having to do a manual install.
=> Use latest Bundler

lib/bundle/brewfile.rb, lib/bundle/dumper.rb, spec/bundle/brewfile_spec.rb
Correctly write to stdout in this case.
Fixes #426.
=> Fix `brew bundle dump --file=-`

.rubocop.yml, .rubocop_shared.yml, spec/bundle/brew_dumper_spec.rb
And fix the one violation still present
=> Synchronizes Rubocop configuration with homebrew/brew

spec/bundle/commands/dump_command_spec.rb
=> Use and_yield instead of passing a block

cmd/brew-bundle.rb
This is for better consistency with Homebrew's other commands.
=> brew-bundle: tweak help output.

cmd/brew-bundle.rb, lib/bundle/brew_dumper.rb, lib/bundle/brew_installer.rb, lib/bundle/brew_services.rb, lib/bundle/bundle.rb, lib/bundle/cask_installer.rb, lib/bundle/commands/cleanup.rb, lib/bundle/commands/exec.rb, lib/bundle/dsl.rb, lib/bundle/dumper.rb, lib/bundle/mac_app_store_installer.rb, lib/bundle/tap_installer.rb
Found while troubleshooting a failing build on https://github.com/Homebrew/homebrew-bundle/pull/452. Re-run its tests when this is merged.
=> Satisfies new style requirements for newline after guards

Rakefile, cmd/brew-bundle.rb
Add a couple of missing frozen_string_literal comments.
=> Add missing frozen_string_literal

lib/bundle/brew_installer.rb, spec/bundle/brew_installer_spec.rb
Link formulae that are unlinked and not keg only.
Fixes https://github.com/Homebrew/homebrew-bundle/issues/468
=> install: Ensure all formulae are linked

README.md
See https://github.com/Homebrew/homebrew-bundle/issues/506
=> Add example of Caskroom tap to `Brewfile` in README

README.md
- Alphabetize the list of things, and put `tap` lines at the top.
- Don't include formulae options, as they have been deprecated for some
time and won't work.
- Use a standard `homebrew/core` tap, not one from BitBucket?!
- Use homebrew/cask-fonts instead of caskroom/fonts.
- Add blank lines for readability.
=> README: Update Brewfile example

README.md, azure-pipelines.yml, lib/bundle/bundle.rb, lib/bundle/extend/os/bundle.rb, lib/bundle/extend/os/linux/bundle.rb, lib/bundle/extend/os/linux/skipper.rb, lib/bundle/extend/os/skipper.rb, lib/bundle/skipper.rb, spec/bundle/commands/check_command_spec.rb, spec/bundle/skipper_spec.rb, spec/bundle_utils_spec.rb, spec/spec_helper.rb, spec/stub/os.rb, spec/stub/utils/formatter.rb
Handle and document enough Linux functionality to call it "supported".
=> Linux support

.github/workflows/tests.yml, spec/spec_helper.rb
=> GitHub Actions CI PRs

lib/bundle/cask_dumper.rb
=> cask_dumper: handle empty cask list.

lib/bundle/locker.rb
Fixes https://github.com/Homebrew/homebrew-bundle/issues/583
=> locker: handle nil error.

README.md
Updating the docs to mention the `HOMEBREW_BUNDLE_FILE` env var.
=> Update docs to mention HOMEBREW_BUNDLE_FILE

README.md, lib/bundle/cask_dumper.rb, lib/bundle/commands/cleanup.rb, lib/bundle/dsl.rb, spec/bundle/dsl_spec.rb
Also print a warning so people adjust their `Brewfile`s accordingly so they work consistently.
Fixes https://github.com/Homebrew/homebrew-bundle/issues/598
=> Always use short names for casks.

lib/bundle/locker.rb, spec/bundle/brew_dumper_spec.rb, spec/bundle/brew_installer_spec.rb, spec/bundle/brew_services_spec.rb, spec/bundle/cask_installer_spec.rb, spec/bundle/commands/cleanup_command_spec.rb, spec/bundle/locker_spec.rb, spec/bundle/mac_app_store_installer_spec.rb, spec/bundle/skipper_spec.rb, spec/bundle/tap_installer_spec.rb
This could occur if the Brewfile was `/dev/stdin` or `/dev/stdout` (e.g. when `-` is used).
=> locker: don't try to write to /dev.

lib/bundle/commands/cleanup.rb, lib/bundle/dumper.rb, spec/bundle/commands/cleanup_command_spec.rb, spec/bundle/commands/dump_command_spec.rb, spec/bundle/dumper_spec.rb
This has been removed from Homebrew/brew.
Fixes #626
=> Fix use of ARGV.force?

lib/bundle/cask_installer.rb, lib/bundle/dsl.rb, spec/bundle/dsl_spec.rb
=> Pass full cask names to `brew cask install` or `upgrade`

cmd/bundle.rb
This is more consistent with other commands (and will look better in a manpage).
=> cmd/bundle: tweak help output.

lib/bundle/locker.rb
Fixes https://github.com/Homebrew/homebrew-bundle/issues/657
=> locker: don't try to get Casks or Mac Apps on non-macOS.

cmd/bundle.rb, lib/bundle/brew_dumper.rb, lib/bundle/brew_installer.rb, lib/bundle/bundle.rb, lib/bundle/checker.rb, lib/bundle/commands/check.rb, lib/bundle/commands/exec.rb, lib/bundle/dsl.rb, lib/bundle/installer.rb, lib/bundle/locker.rb, lib/bundle/mac_app_store_checker.rb, lib/bundle/mac_app_store_dumper.rb, lib/bundle/mac_app_store_installer.rb, lib/bundle/whalebrew_installer.rb, spec/bundle/commands/check_command_spec.rb, spec/bundle/locker_spec.rb, spec/bundle/whalebrew_dumper_spec.rb, spec/bundle/whalebrew_installer_spec.rb, spec/spec_helper.rb, spec/stub/object.rb
These were failing due to missing includes (fixed in https://github.com/Homebrew/brew/pull/7253).
=> Fix `brew style` failures.

lib/bundle/brew_installer.rb
Needed for new checks in https://github.com/Homebrew/brew/pull/7377.
=> brew_installer: fix brew style.

lib/bundle/brew_service_checker.rb, lib/bundle/checker.rb, lib/bundle/mac_app_store_checker.rb, spec/bundle/commands/check_command_spec.rb
=> checker: clarify failure message with --no-upgrade.

spec/bundle/commands/list_command_spec.rb
For https://github.com/Homebrew/brew/pull/7551.
=> list_command_spec: fix brew style.

lib/bundle/brew_dumper.rb, lib/bundle/whalebrew_dumper.rb
Needed for https://github.com/Homebrew/brew/pull/7622
=> Rubocop performance tweaks

lib/bundle/mac_app_store_dumper.rb
For https://github.com/Homebrew/brew/pull/7677
=> mac_app_store_dumper: fix brew style.

lib/bundle/dumper.rb
For https://github.com/Homebrew/brew/pull/7923.
=> dumper: fix style.

spec/bundle/commands/check_command_spec.rb, spec/spec_helper.rb, spec/stub/global.rb
Needed for https://github.com/Homebrew/brew/pull/7867
=> Fix brew style.

lib/bundle/installer.rb
Fixes https://github.com/Homebrew/homebrew-bundle/issues/749.
=> Fix passing options to `install` methods.

lib/bundle/brew_dumper.rb, spec/bundle/brew_dumper_spec.rb
=> Adds support for multi-line desc in brew formulae

cmd/bundle.rb
This matches Homebrew/brew more closely.
=> bundle: provide --formulae flag.

lib/bundle/commands/install.rb
Fixes https://github.com/Homebrew/homebrew-bundle/issues/763.
=> Fix missing `verbose`.

cmd/bundle.rb
Make consistent with (incoming) Homebrew/brew changes.
=> cmd/bundle: fix arg names.

lib/bundle/commands/cleanup.rb, lib/bundle/dumper.rb, lib/bundle/locker.rb
Needed for https://github.com/Homebrew/brew/pull/8297.
=> lib: fix rubocop failures.

Gemfile, Guardfile, lib/bundle/brew_services.rb, lib/bundle/checker.rb, lib/bundle/extend/os/bundle.rb, lib/bundle/extend/os/skipper.rb, spec/stub/exceptions.rb
Needed for Homebrew/brew#8542.
=> Fix RuboCop violations.

lib/bundle/brew_installer.rb
For https://github.com/Homebrew/brew/pull/8556
=> Fix brew style

lib/bundle/brew_installer.rb, lib/bundle/cask_installer.rb, lib/bundle/commands/cleanup.rb, spec/bundle/brew_installer_spec.rb, spec/bundle/cask_installer_spec.rb, spec/bundle/commands/cleanup_command_spec.rb
Fixes https://github.com/Homebrew/homebrew-bundle/issues/815 and closes https://github.com/Homebrew/homebrew-bundle/pull/816.
=> Switch to non-cask commands.

lib/bundle/locker.rb, spec/bundle/locker_spec.rb
Possible fix for https://github.com/Homebrew/homebrew-bundle/issues/822
=> Fix formulae parsing issue

lib/bundle/brew_dumper.rb
Reverts Homebrew/homebrew-bundle#838
=> Revert "Brew dumper: add missing dependency"

README.md, spec/bundle_utils_spec.rb
Migrate `brew cask install` mentions to `brew install --cask`.
=> Use new cask syntax

lib/bundle/cask_dumper.rb, spec/bundle/cask_dumper_spec.rb
=> cask_dumper: handle languages.

lib/bundle/cask_dumper.rb, lib/bundle/cask_installer.rb, lib/bundle/commands/cleanup.rb, lib/bundle/locker.rb, lib/bundle/tap_dumper.rb, spec/bundle/cask_dumper_spec.rb, spec/bundle/cask_installer_spec.rb, spec/bundle/commands/check_command_spec.rb, spec/bundle/locker_spec.rb, spec/bundle/tap_dumper_spec.rb, spec/bundle/tap_installer_spec.rb, spec/spec_helper.rb, spec/stub/cask/cask.rb, spec/stub/tap.rb
Instead use the native APIs.
While we're here, make some class/module methods private too.
=> Don't shell out for casks or taps.

lib/bundle/locker.rb
=> bundle/locker: handle nil formulae_by_name.

lib/bundle/brew_dumper.rb
Don't use `@formulae_by_full_name` because it can be polluted by other queries.
Fixes #910
=> brew_dumper: change sort! input.

lib/bundle/brew_dumper.rb, spec/bundle/brew_dumper_spec.rb
=> brew_dumper: better handle dependencies that aren't installed.

spec/bundle/brew_dumper_spec.rb, spec/bundle/locker_spec.rb
https://github.com/Homebrew/brew/pull/10594
=> Use consistent array/hash indentation

lib/bundle/brew_dumper.rb
=> brew_dumper: handle non-fullname dependencies.

lib/bundle/bundle.rb, lib/bundle/locker.rb, lib/bundle/whalebrew_dumper.rb
=> lib/bundle: fix Style/RedundantBegin offences

lib/bundle/brew_dumper.rb, lib/bundle/skipper.rb, spec/bundle/brew_dumper_spec.rb, spec/stub/formula.rb
These are still an edge-case in homebrew/core.
=> Don't skip unneeded or disabled bottles on Apple Silicon.

lib/bundle/installer.rb
Style fixes needed for Homebrew/brew#11664.
=> lib/bundle/installer.rb: style fixes

lib/bundle/brew_dumper.rb, lib/bundle/skipper.rb, spec/bundle/brew_dumper_spec.rb, spec/stub/formula.rb
=> Only skip unbottled formulae from official taps.

lib/bundle/brew_dumper.rb
Catch an error such as the following:
```
$ brew bundle dump --debug
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rubberband.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mosh.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-lfs.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/little-cms.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb …
```
=> brew_dumper.rb: Fix potential unhandled KeyError

lib/bundle/mac_app_store_checker.rb, spec/bundle/commands/list_command_spec.rb
Needed for https://github.com/Homebrew/brew/pull/12620
=> Use `.to_h` instead of `.map.to_h`

spec/bundle/cask_installer_spec.rb, spec/bundle/whalebrew_installer_spec.rb
Done by `brew style --fix` for https://github.com/Homebrew/brew/pull/12937.
=> Fix RSpec style.

lib/bundle/brewfile.rb, spec/bundle/brewfile_spec.rb
For https://github.com/Homebrew/brew/pull/13433
=> bundle/brewfile: fix ENV style issues

lib/bundle/installer.rb
For https://github.com/Homebrew/brew/pull/13477
=> brew style --fix

lib/bundle/locker.rb, spec/bundle/brew_dumper_spec.rb, spec/bundle/locker_spec.rb, spec/stub/development_tools.rb, spec/stub/utils/popen.rb
This will be renamed in https://github.com/Homebrew/brew/pull/13577
=> bundle/locker: handle DevelopmentTools.gcc_version

lib/bundle/brew_services.rb, spec/bundle/brew_services_spec.rb
Doh. Missed this addition in #1115: actually implementing BrewServices.start!
=> Expose BrewServices.start to fix #1115

spec/bundle/brew_installer_spec.rb, spec/bundle/cask_installer_spec.rb, spec/bundle/mac_app_store_installer_spec.rb, spec/bundle/tap_installer_spec.rb, spec/bundle/whalebrew_installer_spec.rb
This is a prerequisite to https://github.com/Homebrew/brew/pull/14419
cc @MikeMcQuaid @apainintheneck
=> Resolve RSpec/NoExpectationExample violations

spec/bundle/brew_dumper_spec.rb, spec/bundle/cask_installer_spec.rb, spec/bundle/commands/check_command_spec.rb, spec/bundle/commands/list_command_spec.rb, spec/bundle/tap_dumper_spec.rb
Needed for https://github.com/Homebrew/brew/pull/15136.
=> `brew style --fix`

lib/bundle/commands/exec.rb
This is to unblock https://github.com/Homebrew/brew/pull/15265
=> Apply Style/InvertibleUnlessCondition cop

.github/workflows/tests.yml, lib/bundle/bundle.rb
Reverts Homebrew/homebrew-bundle#1272
Fixes #1275
=> Revert "Run tests on Ruby 3.1"

lib/bundle/skipper.rb
For https://github.com/Homebrew/brew/pull/16497.
=> Fix RuboCop `Style/ArrayIntersect` offenses

lib/bundle/dsl.rb
For https://github.com/Homebrew/brew/pull/16501.
=> Fix RuboCop `Style/RedundantFreeze` offenses

lib/bundle/brew_dumper.rb, lib/bundle/brew_installer.rb, lib/bundle/brew_services.rb, lib/bundle/cask_installer.rb, spec/spec_helper.rb
- For https://github.com/Homebrew/brew/pull/16745.
=> Fix RuboCop `Lint/RedundantDirGlobSort` and `Performance/MapCompact` offenses

README.md
Clarify what we are looking for in new installers/checkers/dumpers and what we are not looking for.
=> README: add a section about new installers/checkers/dumpers.

lib/bundle/cask_dumper.rb
solve  https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/config.rb#L197
=> add explicit_s method from `Cask#Config` of `homebrew/brew` 

lib/bundle/brew_installer.rb, spec/bundle/brew_services_spec.rb
=> chore: fix typo

cmd/bundle.rb
Needed to unblock https://github.com/Homebrew/brew/pull/19143
=> bundle: fix help spacing.

cmd/bundle.rb
Seen in https://github.com/Homebrew/brew/pull/19440.
=> cmd/bundle: fix spacing
